export type Locale = "es" | "pt" | "en";
export type Track = "foundation" | "software" | "ai" | "cloud" | "cybersecurity" | "research" | "creative";
export type Mastery = "A" | "B" | "C" | "D" | "E" | "F";

export type Localized = Record<Locale, string>;

export type Course = {
  code: string;
  semester: number;
  credits: number;
  hours: number;
  track: Track;
  entry: Mastery;
  exit: Mastery;
  title: Localized;
  summary: Localized;
  prerequisites: string[];
};

export type CourseDetail = {
  objectives: Record<Locale, string[]>;
  competencies: Record<Locale, string[]>;
  syllabus: Record<Locale, string[]>;
  exercises: Record<Locale, string[]>;
  lab: Localized;
  project: Localized;
  aiPolicy: Localized;
  resources: Array<{ title: string; url: string; type: "Official docs" | "Repository" | "Paper" | "Lab" | "Dataset"; access: "FREE" | "OPEN SOURCE" | "COMMERCIAL"; license?: string }>;
  assessment: Array<{ label: Localized; weight: number }>;
  rubric: Array<{ criterion: Localized; weight: number }>;
};

const l = (es: string, pt: string, en: string): Localized => ({ es, pt, en });
const units = (es: string[], pt: string[], en: string[]): Record<Locale, string[]> => ({ es, pt, en });

export const program = {
  code: "DICT",
  version: "v1.0",
  totalCredits: 300,
  creditName: l("Créditos Académicos Internos (CA)", "Créditos Académicos Internos (CA)", "Créditos Académicos Internos (CA)"),
  disclaimer: l(
    "D.I.C.T. es formación académica independiente. No es una titulación universitaria oficial, no atribuye reconocimiento estatal y los CA no son ECTS.",
    "D.I.C.T. é uma formação académica independente. Não é um diploma universitário oficial, não atribui reconhecimento estatal e os CA não são ECTS.",
    "D.I.C.T. is independent academic education. It is not an official university degree, does not confer state recognition, and CA are not ECTS credits.",
  ),
};

export const courses: Course[] = [
  { code: "DCT-101", semester: 1, credits: 10, hours: 250, track: "foundation", entry: "A", exit: "B", title: l("Fundamentos Digitales y Computación", "Fundamentos Digitais e Computação", "Digital Foundations & Computing"), summary: l("Sistemas, terminal, internet, Git y pensamiento computacional.", "Sistemas, terminal, internet, Git e pensamento computacional.", "Systems, terminal, internet, Git and computational thinking."), prerequisites: [] },
  { code: "DCT-102", semester: 1, credits: 10, hours: 250, track: "foundation", entry: "A", exit: "B", title: l("Programación I con Python", "Programação I com Python", "Programming I with Python"), summary: l("Algoritmos, funciones, datos y depuración.", "Algoritmos, funções, dados e depuração.", "Algorithms, functions, data and debugging."), prerequisites: [] },
  { code: "DCT-103", semester: 1, credits: 10, hours: 250, track: "foundation", entry: "A", exit: "B", title: l("Matemáticas y Método Académico I", "Matemática e Método Académico I", "Mathematics & Academic Method I"), summary: l("Lógica, funciones, estudio y escritura técnica.", "Lógica, funções, estudo e escrita técnica.", "Logic, functions, study and technical writing."), prerequisites: [] },
  { code: "DCT-104", semester: 2, credits: 10, hours: 250, track: "software", entry: "B", exit: "B", title: l("Sistemas Web, Git y Colaboración", "Sistemas Web, Git e Colaboração", "Web Systems, Git & Collaboration"), summary: l("HTML, CSS, JavaScript, accesibilidad y revisión.", "HTML, CSS, JavaScript, acessibilidade e revisão.", "HTML, CSS, JavaScript, accessibility and review."), prerequisites: ["DCT-101"] },
  { code: "DCT-105", semester: 2, credits: 10, hours: 250, track: "software", entry: "B", exit: "C", title: l("Programación II y Estructuras de Datos", "Programação II e Estruturas de Dados", "Programming II & Data Structures"), summary: l("Abstracción, colecciones, complejidad y pruebas.", "Abstração, coleções, complexidade e testes.", "Abstraction, collections, complexity and tests."), prerequisites: ["DCT-102"] },
  { code: "DCT-106", semester: 2, credits: 10, hours: 250, track: "foundation", entry: "B", exit: "C", title: l("Matemática Discreta y Estadística", "Matemática Discreta e Estatística", "Discrete Mathematics & Statistics"), summary: l("Probabilidad, inferencia y modelos discretos.", "Probabilidade, inferência e modelos discretos.", "Probability, inference and discrete models."), prerequisites: ["DCT-103"] },
  { code: "DCT-201", semester: 3, credits: 10, hours: 250, track: "software", entry: "C", exit: "C", title: l("Ingeniería de Software y Bases de Datos", "Engenharia de Software e Bases de Dados", "Software Engineering & Databases"), summary: l("Diseño, SQL, modelado, pruebas y documentación.", "Design, SQL, modelagem, testes e documentação.", "Design, SQL, modeling, testing and documentation."), prerequisites: ["DCT-105", "DCT-104"] },
  { code: "DCT-202", semester: 3, credits: 10, hours: 250, track: "cloud", entry: "B", exit: "C", title: l("Sistemas Operativos, Linux y Redes", "Sistemas Operativos, Linux e Redes", "Operating Systems, Linux & Networks"), summary: l("Procesos, shell, TCP/IP, DNS y HTTP.", "Processos, shell, TCP/IP, DNS e HTTP.", "Processes, shell, TCP/IP, DNS and HTTP."), prerequisites: ["DCT-101"] },
  { code: "DCT-203", semester: 3, credits: 10, hours: 250, track: "ai", entry: "C", exit: "C", title: l("Álgebra Lineal, Probabilidad y Optimización", "Álgebra Linear, Probabilidade e Otimização", "Linear Algebra, Probability & Optimization"), summary: l("Vectores, matrices, cálculo y optimización.", "Vetores, matrizes, cálculo e otimização.", "Vectors, matrices, calculus and optimization."), prerequisites: ["DCT-106"] },
  { code: "DCT-204", semester: 4, credits: 10, hours: 250, track: "software", entry: "C", exit: "D", title: l("Desarrollo Full Stack y Seguridad de APIs", "Desenvolvimento Full Stack e Segurança de APIs", "Full-Stack Development & API Security"), summary: l("React, backend, autenticación y autorización.", "React, backend, autenticação e autorização.", "React, backend, authentication and authorization."), prerequisites: ["DCT-201", "DCT-202"] },
  { code: "DCT-205", semester: 4, credits: 10, hours: 250, track: "software", entry: "C", exit: "D", title: l("Algoritmos, Arquitectura y Calidad", "Algoritmos, Arquitetura e Qualidade", "Algorithms, Architecture & Quality"), summary: l("Algoritmos, patrones, testing y decisiones de arquitectura.", "Algoritmos, padrões, testes e decisões de arquitetura.", "Algorithms, patterns, testing and architecture decisions."), prerequisites: ["DCT-105", "DCT-201"] },
  { code: "DCT-206", semester: 4, credits: 10, hours: 250, track: "cybersecurity", entry: "C", exit: "D", title: l("Fundamentos de Ciberseguridad", "Fundamentos de Cibersegurança", "Cybersecurity Foundations"), summary: l("Identidad, criptografía, defensa y modelo de amenazas.", "Identidade, criptografia, defesa e modelo de ameaças.", "Identity, cryptography, defense and threat modeling."), prerequisites: ["DCT-202"] },
  { code: "DCT-301", semester: 5, credits: 10, hours: 250, track: "ai", entry: "C", exit: "D", title: l("Machine Learning Aplicado", "Machine Learning Aplicado", "Applied Machine Learning"), summary: l("Modelos supervisados, evaluación y pipelines reproducibles.", "Modelos supervisionados, avaliação e pipelines reprodutíveis.", "Supervised models, evaluation and reproducible pipelines."), prerequisites: ["DCT-105", "DCT-203"] },
  { code: "DCT-302", semester: 5, credits: 10, hours: 250, track: "cloud", entry: "C", exit: "D", title: l("Cloud, DevOps y Entrega Continua", "Cloud, DevOps e Entrega Contínua", "Cloud, DevOps & Continuous Delivery"), summary: l("Contenedores, CI/CD, despliegue y observabilidad.", "Contentores, CI/CD, implantação e observabilidade.", "Containers, CI/CD, deployment and observability."), prerequisites: ["DCT-201", "DCT-202"] },
  { code: "DCT-303", semester: 5, credits: 10, hours: 250, track: "cybersecurity", entry: "D", exit: "D", title: l("Ingeniería de Software Seguro y Web Security Lab", "Engenharia de Software Seguro e Web Security Lab", "Secure Software Engineering & Web Security Lab"), summary: l("Pruebas seguras, hardening y laboratorios autorizados.", "Testes seguros, hardening e laboratórios autorizados.", "Secure testing, hardening and authorized labs."), prerequisites: ["DCT-204", "DCT-206"] },
  { code: "DCT-304", semester: 6, credits: 10, hours: 250, track: "ai", entry: "D", exit: "D", title: l("Deep Learning y Computer Vision", "Deep Learning e Computer Vision", "Deep Learning & Computer Vision"), summary: l("Redes neuronales, visión, embeddings y evaluación.", "Redes neuronais, visão, embeddings e avaliação.", "Neural networks, vision, embeddings and evaluation."), prerequisites: ["DCT-301"] },
  { code: "DCT-305", semester: 6, credits: 10, hours: 250, track: "ai", entry: "D", exit: "D", title: l("Ingeniería de Datos y Analítica", "Engenharia de Dados e Analítica", "Data Engineering & Analytics"), summary: l("Calidad, pipelines, consultas, métricas y privacidad.", "Qualidade, pipelines, consultas, métricas e privacidade.", "Quality, pipelines, queries, metrics and privacy."), prerequisites: ["DCT-201", "DCT-301"] },
  { code: "DCT-306", semester: 6, credits: 10, hours: 250, track: "cybersecurity", entry: "D", exit: "D", title: l("Respuesta a Incidentes y Forense Digital", "Resposta a Incidentes e Forense Digital", "Incident Response & Digital Forensics"), summary: l("Logs, triage, contención y preservación de evidencia.", "Logs, triagem, contenção e preservação de evidências.", "Logs, triage, containment and evidence preservation."), prerequisites: ["DCT-206"] },
  { code: "DCT-401", semester: 7, credits: 10, hours: 250, track: "ai", entry: "D", exit: "E", title: l("Ingeniería de LLM y RAG", "Engenharia de LLM e RAG", "LLM Engineering & RAG"), summary: l("Transformers, recuperación, evaluación y guardrails.", "Transformers, recuperação, avaliação e guardrails.", "Transformers, retrieval, evaluation and guardrails."), prerequisites: ["DCT-304", "DCT-305"] },
  { code: "DCT-402", semester: 7, credits: 10, hours: 250, track: "cloud", entry: "D", exit: "E", title: l("MLOps, IA Local y Serving", "MLOps, IA Local e Serving", "MLOps, Local AI & Serving"), summary: l("Registro de modelos, serving, cuantización y privacidad.", "Registo de modelos, serving, quantização e privacidade.", "Model registry, serving, quantization and privacy."), prerequisites: ["DCT-301", "DCT-302"] },
  { code: "DCT-403", semester: 7, credits: 10, hours: 250, track: "cybersecurity", entry: "D", exit: "E", title: l("Seguridad de IA y Sistemas Adversariales", "Segurança de IA e Sistemas Adversariais", "AI Security & Adversarial Systems"), summary: l("Riesgos de LLM, agentes, datos y cadena de suministro.", "Riscos de LLM, agentes, dados e cadeia de fornecimento.", "LLM, agent, data and supply-chain risks."), prerequisites: ["DCT-401", "DCT-303"] },
  { code: "DCT-404", semester: 8, credits: 10, hours: 250, track: "ai", entry: "E", exit: "E", title: l("Computación Agéntica y Orquestación", "Computação Agêntica e Orquestração", "Agentic Computing & Orchestration"), summary: l("Herramientas, planificación, memoria, permisos y evaluación.", "Ferramentas, planeamento, memória, permissões e avaliação.", "Tools, planning, memory, permissions and evaluation."), prerequisites: ["DCT-401", "DCT-403"] },
  { code: "DCT-405", semester: 8, credits: 10, hours: 250, track: "creative", entry: "D", exit: "E", title: l("Sistemas Generativos Visuales y de Audio", "Sistemas Generativos Visuais e de Áudio", "Generative Visual & Audio Systems"), summary: l("Imagen, audio, derechos, evaluación y dirección creativa.", "Imagem, áudio, direitos, avaliação e direção criativa.", "Image, audio, rights, evaluation and creative direction."), prerequisites: ["DCT-304"] },
  { code: "DCT-406", semester: 8, credits: 10, hours: 250, track: "cloud", entry: "D", exit: "E", title: l("Arquitectura Cloud Segura", "Arquitetura Cloud Segura", "Secure Cloud Architecture"), summary: l("Identidad, redes, secretos, coste y resiliencia.", "Identidade, redes, segredos, custo e resiliência.", "Identity, networks, secrets, cost and resilience."), prerequisites: ["DCT-302", "DCT-303"] },
  { code: "DCT-501", semester: 9, credits: 10, hours: 250, track: "research", entry: "E", exit: "F", title: l("Investigación, Producto y Tecnología Responsable", "Investigação, Produto e Tecnologia Responsável", "Research, Product & Responsible Technology"), summary: l("Papers, experimentos, impacto, licencias y producto.", "Papers, experiências, impacto, licenças e produto.", "Papers, experiments, impact, licensing and product."), prerequisites: ["DCT-401", "DCT-403"] },
  { code: "DCT-502", semester: 9, credits: 10, hours: 250, track: "creative", entry: "E", exit: "F", title: l("Studio de Especialización", "Estúdio de Especialização", "Specialization Studio"), summary: l("Estudio dirigido en IA, seguridad, cloud o tecnología creativa.", "Estúdio orientado em IA, segurança, cloud ou tecnologia criativa.", "Directed studio in AI, security, cloud or creative technology."), prerequisites: ["DCT-404"] },
  { code: "DCT-503", semester: 9, credits: 10, hours: 250, track: "software", entry: "E", exit: "F", title: l("Ingeniería de Sistemas a Escala", "Engenharia de Sistemas em Escala", "Systems Engineering at Scale"), summary: l("Diseño distribuido, fiabilidad, coste y comunicación técnica.", "Design distribuído, fiabilidade, custo e comunicação técnica.", "Distributed design, reliability, cost and technical communication."), prerequisites: ["DCT-302", "DCT-205"] },
  { code: "DCT-504", semester: 10, credits: 10, hours: 250, track: "research", entry: "F", exit: "F", title: l("Capstone: Investigación y Prototipo", "Capstone: Investigação e Protótipo", "Capstone: Research & Prototype"), summary: l("Pregunta, evidencia, arquitectura, prototipo y revisión crítica.", "Pergunta, evidência, arquitetura, protótipo e revisão crítica.", "Question, evidence, architecture, prototype and critical review."), prerequisites: ["DCT-501", "DCT-503"] },
  { code: "DCT-505", semester: 10, credits: 10, hours: 250, track: "research", entry: "F", exit: "F", title: l("Capstone: Despliegue y Aseguramiento", "Capstone: Implantação e Garantia", "Capstone: Deployment & Assurance"), summary: l("Pruebas, despliegue, seguridad, observabilidad y documentación.", "Testes, implantação, segurança, observabilidade e documentação.", "Testing, deployment, security, observability and documentation."), prerequisites: ["DCT-504"] },
  { code: "DCT-506", semester: 10, credits: 10, hours: 250, track: "research", entry: "F", exit: "F", title: l("Capstone: Defensa y Portfolio", "Capstone: Defesa e Portfólio", "Capstone: Defense & Portfolio"), summary: l("Defensa oral, portfolio público y cierre de expediente interno.", "Defesa oral, portfólio público e fecho de registo académico interno.", "Oral defense, public portfolio and internal-record completion."), prerequisites: ["DCT-505"] },
];

const sharedAssessment = [
  { label: l("Teoría y quizzes", "Teoria e quizzes", "Theory & quizzes"), weight: 15 },
  { label: l("Laboratorio", "Laboratório", "Laboratory"), weight: 30 },
  { label: l("Proyecto", "Projeto", "Project"), weight: 35 },
  { label: l("Investigación y documentación", "Investigação e documentação", "Research & documentation"), weight: 10 },
  { label: l("Examen o defensa", "Exame ou defesa", "Exam or defense"), weight: 10 },
];

const sharedRubric = [
  { criterion: l("Corrección y profundidad", "Correção e profundidade", "Correctness & depth"), weight: 25 },
  { criterion: l("Arquitectura y seguridad", "Arquitetura e segurança", "Architecture & security"), weight: 25 },
  { criterion: l("Calidad y reproducibilidad", "Qualidade e reprodutibilidade", "Quality & reproducibility"), weight: 25 },
  { criterion: l("Documentación y defensa", "Documentação e defesa", "Documentation & defense"), weight: 25 },
];

export const detailedCourses: Record<string, CourseDetail> = {
  "DCT-301": {
    objectives: units(["Construir un pipeline supervisado reproducible.", "Comparar modelos mediante métricas y validación cruzada.", "Explicar sesgo, sobreajuste y límites de una predicción."], ["Construir um pipeline supervisionado reprodutível.", "Comparar modelos através de métricas e validação cruzada.", "Explicar viés, sobreajuste e limites de uma previsão."], ["Build a reproducible supervised pipeline.", "Compare models with metrics and cross-validation.", "Explain bias, overfitting and prediction limits."]),
    competencies: units(["Preparación y trazabilidad de datos.", "Evaluación responsable de modelos.", "Comunicación técnica basada en evidencia."], ["Preparação e rastreabilidade de dados.", "Avaliação responsável de modelos.", "Comunicação técnica baseada em evidência."], ["Data preparation and traceability.", "Responsible model evaluation.", "Evidence-based technical communication."]),
    syllabus: units(["Regresión y clasificación", "Ingeniería de variables", "Validación, métricas y error", "Pipelines, experimentos y reproducibilidad"], ["Regressão e classificação", "Engenharia de variáveis", "Validação, métricas e erro", "Pipelines, experiências e reprodutibilidade"], ["Regression and classification", "Feature engineering", "Validation, metrics and error", "Pipelines, experiments and reproducibility"]),
    exercises: units(["Analizar un conjunto de datos documentado.", "Comparar tres modelos con el mismo protocolo.", "Redactar una nota de límites y riesgos."], ["Analisar um conjunto de dados documentado.", "Comparar três modelos com o mesmo protocolo.", "Redigir uma nota de limites e riscos."], ["Analyze a documented dataset.", "Compare three models with the same protocol.", "Write a limitations and risks note."]),
    lab: l("AI Lab: clasificación reproducible con rutas CPU y GPU opcional.", "AI Lab: classificação reprodutível com rotas CPU e GPU opcional.", "AI Lab: reproducible classification with CPU and optional GPU paths."),
    project: l("Entregar un sistema de predicción con modelo, evaluación, modelo de datos y README reproducible.", "Entregar um sistema de previsão com modelo, avaliação, modelo de dados e README reprodutível.", "Deliver a prediction system with model, evaluation, data model and reproducible README."),
    aiPolicy: l("Se permite IA para explicar errores y mejorar documentación; deben declararse las aportaciones y no puede generar íntegramente la entrega evaluada.", "É permitida IA para explicar erros e melhorar documentação; os contributos devem ser declarados e não pode gerar integralmente a entrega avaliada.", "AI may explain errors and improve documentation; contributions must be disclosed and it may not generate the whole assessed submission."),
    resources: [{ title: "scikit-learn User Guide", url: "https://scikit-learn.org/stable/user_guide.html", type: "Official docs", access: "FREE" }, { title: "UCI Machine Learning Repository", url: "https://archive.ics.uci.edu/", type: "Dataset", access: "FREE" }],
    assessment: sharedAssessment, rubric: sharedRubric,
  },
  "DCT-401": {
    objectives: units(["Explicar el ciclo de vida de una aplicación LLM.", "Diseñar un RAG evaluable con recuperación y citas.", "Aplicar límites de seguridad y privacidad al uso de modelos."], ["Explicar o ciclo de vida de uma aplicação LLM.", "Desenhar um RAG avaliável com recuperação e citações.", "Aplicar limites de segurança e privacidade ao uso de modelos."], ["Explain the lifecycle of an LLM application.", "Design an evaluable RAG with retrieval and citations.", "Apply security and privacy boundaries to model use."]),
    competencies: units(["Diseño de recuperación y evaluación.", "Uso responsable de modelos y datos.", "Implementación de guardrails verificables."], ["Desenho de recuperação e avaliação.", "Uso responsável de modelos e dados.", "Implementação de guardrails verificáveis."], ["Retrieval and evaluation design.", "Responsible model and data use.", "Verifiable guardrail implementation."]),
    syllabus: units(["Transformers y embeddings", "Chunking, recuperación y RAG", "Evaluación y alucinación", "Fine-tuning, cuantización y guardrails"], ["Transformers e embeddings", "Chunking, recuperação e RAG", "Avaliação e alucinação", "Fine-tuning, quantização e guardrails"], ["Transformers and embeddings", "Chunking, retrieval and RAG", "Evaluation and hallucination", "Fine-tuning, quantization and guardrails"]),
    exercises: units(["Evaluar recuperación con un conjunto de preguntas trazable.", "Comparar políticas de partición de documentos.", "Diseñar pruebas para salidas inseguras."], ["Avaliar recuperação com um conjunto de perguntas rastreável.", "Comparar políticas de divisão de documentos.", "Desenhar testes para saídas inseguras."], ["Evaluate retrieval with a traceable question set.", "Compare document chunking policies.", "Design tests for unsafe outputs."]),
    lab: l("LLM Lab: construir un asistente RAG local o de baja escala, con fuentes visibles y evaluación documentada.", "LLM Lab: construir um assistente RAG local ou de baixa escala, com fontes visíveis e avaliação documentada.", "LLM Lab: build a local or low-scale RAG assistant with visible sources and documented evaluation."),
    project: l("Diseñar y defender un RAG de dominio limitado con trazabilidad de fuentes, conjunto de evaluación y controles de salida.", "Desenhar e defender um RAG de domínio limitado com rastreabilidade de fontes, conjunto de avaliação e controlos de saída.", "Design and defend a limited-domain RAG with source traceability, an evaluation set and output controls."),
    aiPolicy: l("El uso de LLM es parte del objeto de estudio. Deben registrarse prompts, modelos, datos y validaciones; las afirmaciones del informe requieren verificación propia.", "O uso de LLM faz parte do objeto de estudo. Devem ser registados prompts, modelos, dados e validações; as afirmações do relatório requerem verificação própria.", "LLM use is part of the subject. Prompts, models, data and validations must be logged; report claims require the student's own verification."),
    resources: [{ title: "Hugging Face LLM Course", url: "https://huggingface.co/learn/llm-course/en/chapter1/1", type: "Official docs", access: "FREE" }, { title: "OWASP LLM Top 10", url: "https://genai.owasp.org/llm-top-10/", type: "Official docs", access: "FREE" }, { title: "llm-course", url: "https://github.com/mlabonne/llm-course", type: "Repository", access: "OPEN SOURCE", license: "Apache-2.0" }],
    assessment: sharedAssessment, rubric: sharedRubric,
  },
  "DCT-403": {
    objectives: units(["Modelar riesgos para aplicaciones LLM y agentes.", "Diseñar mitigaciones verificables para entrada, salida, herramientas y datos.", "Explicar la seguridad de IA sin ejecutar actividades contra sistemas no autorizados."], ["Modelar riscos para aplicações LLM e agentes.", "Desenhar mitigações verificáveis para entrada, saída, ferramentas e dados.", "Explicar a segurança de IA sem executar atividades contra sistemas não autorizados."], ["Model risks for LLM applications and agents.", "Design verifiable mitigations for input, output, tools and data.", "Explain AI security without conducting activity against unauthorized systems."]),
    competencies: units(["Modelado de amenazas de IA.", "Pruebas de seguridad en entorno aislado.", "Gobernanza y evidencia de control."], ["Modelação de ameaças de IA.", "Testes de segurança em ambiente isolado.", "Governança e evidência de controlo."], ["AI threat modeling.", "Security testing in an isolated environment.", "Governance and control evidence."]),
    syllabus: units(["Inyección de instrucciones y fuga de datos", "Cadena de suministro y envenenamiento", "Agencia excesiva y abuso de herramientas", "Embeddings, RAG y gobernanza"], ["Injeção de instruções e fuga de dados", "Cadeia de fornecimento e envenenamento", "Agência excessiva e abuso de ferramentas", "Embeddings, RAG e governança"], ["Prompt injection and data leakage", "Supply chain and poisoning", "Excessive agency and tool abuse", "Embeddings, RAG and governance"]),
    exercises: units(["Elaborar un modelo de amenazas para un asistente interno.", "Definir pruebas de aceptación de seguridad.", "Documentar una mitigación con criterios de verificación."], ["Elaborar um modelo de ameaças para um assistente interno.", "Definir testes de aceitação de segurança.", "Documentar uma mitigação com critérios de verificação."], ["Create a threat model for an internal assistant.", "Define security acceptance tests.", "Document a mitigation with verification criteria."]),
    lab: l("AI Security Lab: analizar un sistema de práctica, con datos sintéticos y permisos mínimos; no se atacan sistemas externos.", "AI Security Lab: analisar um sistema de prática, com dados sintéticos e permissões mínimas; não se atacam sistemas externos.", "AI Security Lab: analyze a practice system with synthetic data and least privilege; external systems are never targeted."),
    project: l("Auditar una aplicación de IA de laboratorio y entregar matriz de riesgos, pruebas, mitigaciones y plan de seguimiento.", "Auditar uma aplicação de IA de laboratório e entregar matriz de riscos, testes, mitigações e plano de acompanhamento.", "Audit a laboratory AI application and deliver a risk matrix, tests, mitigations and follow-up plan."),
    aiPolicy: l("La IA puede ser objeto de prueba bajo protocolo del laboratorio. No se permite solicitar ni ejecutar acciones contra servicios externos o datos reales no autorizados.", "A IA pode ser objeto de teste sob protocolo do laboratório. Não é permitido solicitar nem executar ações contra serviços externos ou dados reais não autorizados.", "AI may be tested under the lab protocol. Requests or actions against external services or unauthorized real data are prohibited."),
    resources: [{ title: "OWASP GenAI Security Project", url: "https://genai.owasp.org/", type: "Official docs", access: "FREE" }, { title: "NIST AI 600-1", url: "https://doi.org/10.6028/NIST.AI.600-1", type: "Paper", access: "FREE" }],
    assessment: sharedAssessment, rubric: sharedRubric,
  },
  "DCT-303": {
    objectives: units(["Aplicar prácticas de desarrollo seguro en aplicaciones web.", "Identificar clases de riesgo en un laboratorio autorizado.", "Redactar hallazgos con priorización y mitigación."], ["Aplicar práticas de desenvolvimento seguro em aplicações web.", "Identificar classes de risco num laboratório autorizado.", "Redigir conclusões com priorização e mitigação."], ["Apply secure development practices in web applications.", "Identify risk classes in an authorized lab.", "Write findings with prioritization and mitigation."]),
    competencies: units(["Modelado de amenazas web.", "Verificación de configuración y autorización.", "Comunicación responsable de vulnerabilidades."], ["Modelação de ameaças web.", "Verificação de configuração e autorização.", "Comunicação responsável de vulnerabilidades."], ["Web threat modeling.", "Configuration and authorization verification.", "Responsible vulnerability communication."]),
    syllabus: units(["Autenticación y autorización", "Validación y manejo de salida", "Configuración y dependencias", "Pruebas y reporte de seguridad"], ["Autenticação e autorização", "Validação e tratamento de saída", "Configuração e dependências", "Testes e relatório de segurança"], ["Authentication and authorization", "Validation and output handling", "Configuration and dependencies", "Security testing and reporting"]),
    exercises: units(["Revisar controles de sesión de una aplicación local.", "Crear pruebas de autorización.", "Priorizar un hallazgo y proponer una corrección."], ["Rever controlos de sessão de uma aplicação local.", "Criar testes de autorização.", "Priorizar uma conclusão e propor uma correção."], ["Review session controls in a local application.", "Create authorization tests.", "Prioritize a finding and propose a fix."]),
    lab: l("Web Security Lab: aplicación vulnerable local o aislada; cada sesión comienza con una declaración de alcance autorizado.", "Web Security Lab: aplicação vulnerável local ou isolada; cada sessão começa com uma declaração de âmbito autorizado.", "Web Security Lab: local or isolated vulnerable application; each session begins with an authorized-scope declaration."),
    project: l("Diseñar un plan de hardening y automatizar pruebas defensivas para una aplicación de demostración.", "Desenhar um plano de hardening e automatizar testes defensivos para uma aplicação de demonstração.", "Design a hardening plan and automate defensive tests for a demonstration application."),
    aiPolicy: l("La IA puede explicar vulnerabilidades y ayudar a revisar código; el alumno debe validar cada hallazgo y no puede usarla para atacar objetivos reales.", "A IA pode explicar vulnerabilidades e ajudar a rever código; o aluno deve validar cada conclusão e não pode utilizá-la para atacar alvos reais.", "AI may explain vulnerabilities and help review code; the student must validate every finding and may not use it to attack real targets."),
    resources: [{ title: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/", type: "Official docs", access: "FREE" }, { title: "OWASP Juice Shop", url: "https://github.com/juice-shop/juice-shop", type: "Lab", access: "OPEN SOURCE", license: "MIT" }],
    assessment: sharedAssessment, rubric: sharedRubric,
  },
  "DCT-504": {
    objectives: units(["Formular una pregunta técnica o de investigación defendible.", "Construir un prototipo con arquitectura, evaluación y trazabilidad.", "Preparar evidencia para una revisión crítica y una defensa."], ["Formular uma questão técnica ou de investigação defensável.", "Construir um protótipo com arquitetura, avaliação e rastreabilidade.", "Preparar evidências para revisão crítica e defesa."], ["Formulate a defensible technical or research question.", "Build a prototype with architecture, evaluation and traceability.", "Prepare evidence for critical review and defense."]),
    competencies: units(["Diseño de experimentos.", "Arquitectura y seguridad de producto.", "Escritura y defensa técnica."], ["Desenho de experiências.", "Arquitetura e segurança de produto.", "Escrita e defesa técnica."], ["Experiment design.", "Product architecture and security.", "Technical writing and defense."]),
    syllabus: units(["Pregunta y revisión bibliográfica", "Datos, métodos y reproducibilidad", "Arquitectura, pruebas y riesgos", "Presentación y revisión por pares"], ["Questão e revisão bibliográfica", "Dados, métodos e reprodutibilidade", "Arquitetura, testes e riscos", "Apresentação e revisão por pares"], ["Question and literature review", "Data, methods and reproducibility", "Architecture, testing and risks", "Presentation and peer review"]),
    exercises: units(["Escribir propuesta de una página.", "Registrar un protocolo de experimento.", "Realizar una revisión cruzada de arquitectura."], ["Escrever proposta de uma página.", "Registar um protocolo de experiência.", "Realizar uma revisão cruzada de arquitetura."], ["Write a one-page proposal.", "Record an experiment protocol.", "Conduct a cross-architecture review."]),
    lab: l("Research & Product Lab: trabajo guiado con repositorio, registro de decisiones y revisiones periódicas.", "Research & Product Lab: trabalho orientado com repositório, registo de decisões e revisões periódicas.", "Research & Product Lab: guided work with a repository, decision log and recurring reviews."),
    project: l("Entregar un prototipo, informe técnico, evaluación, análisis de riesgos, plan de despliegue y presentación para la defensa final.", "Entregar um protótipo, relatório técnico, avaliação, análise de riscos, plano de implantação e apresentação para a defesa final.", "Deliver a prototype, technical report, evaluation, risk analysis, deployment plan and final-defense presentation."),
    aiPolicy: l("La IA puede apoyar ideación, revisión de estilo y ejercicios de entrevista si se declara. No reemplaza la investigación, el razonamiento ni la defensa del estudiante.", "A IA pode apoiar ideação, revisão de estilo e exercícios de entrevista se for declarada. Não substitui a investigação, o raciocínio nem a defesa do estudante.", "AI may support ideation, style review and interview practice when disclosed. It does not replace the student's research, reasoning or defense."),
    resources: [{ title: "ACM Curricula Recommendations", url: "https://www.acm.org/education/curricula-recommendations", type: "Official docs", access: "FREE" }, { title: "NIST AI 600-1", url: "https://doi.org/10.6028/NIST.AI.600-1", type: "Paper", access: "FREE" }],
    assessment: sharedAssessment, rubric: sharedRubric,
  },
};

export const trackLabels: Record<Track, Localized> = {
  foundation: l("Fundamentos", "Fundamentos", "Foundations"), software: l("Software", "Software", "Software"), ai: l("Inteligencia Artificial", "Inteligência Artificial", "Artificial Intelligence"), cloud: l("Cloud y Sistemas", "Cloud e Sistemas", "Cloud & Systems"), cybersecurity: l("Ciberseguridad", "Cibersegurança", "Cybersecurity"), research: l("Investigación", "Investigação", "Research"), creative: l("Tecnología Creativa", "Tecnologia Criativa", "Creative Technology"),
};

const genericResourcesByTrack: Record<Track, CourseDetail["resources"]> = {
  foundation: [{ title: "MDN Web Docs", url: "https://developer.mozilla.org/", type: "Official docs", access: "FREE" }],
  software: [{ title: "MDN Web Docs", url: "https://developer.mozilla.org/", type: "Official docs", access: "FREE" }, { title: "OWASP Top 10", url: "https://owasp.org/www-project-top-ten/", type: "Official docs", access: "FREE" }],
  ai: [{ title: "Hugging Face Learn", url: "https://huggingface.co/learn", type: "Official docs", access: "FREE" }, { title: "PyTorch Tutorials", url: "https://docs.pytorch.org/tutorials/", type: "Official docs", access: "FREE" }],
  cloud: [{ title: "Docker Documentation", url: "https://docs.docker.com/", type: "Official docs", access: "FREE" }, { title: "GitHub Actions Documentation", url: "https://docs.github.com/actions", type: "Official docs", access: "FREE" }],
  cybersecurity: [{ title: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/", type: "Official docs", access: "FREE" }, { title: "OWASP Juice Shop", url: "https://github.com/juice-shop/juice-shop", type: "Lab", access: "OPEN SOURCE", license: "MIT" }],
  research: [{ title: "ACM Curricula Recommendations", url: "https://www.acm.org/education/curricula-recommendations", type: "Official docs", access: "FREE" }, { title: "NIST AI 600-1", url: "https://doi.org/10.6028/NIST.AI.600-1", type: "Paper", access: "FREE" }],
  creative: [{ title: "Hugging Face Learn", url: "https://huggingface.co/learn", type: "Official docs", access: "FREE" }],
};

function generatedDetail(course: Course): CourseDetail {
  const title = course.title;
  return {
    objectives: units([`Aplicar los fundamentos de ${title.es} en un resultado verificable.`, "Justificar decisiones técnicas con evidencia, pruebas y documentación.", "Identificar límites, riesgos y necesidades de mejora."], [`Aplicar os fundamentos de ${title.pt} num resultado verificável.`, "Justificar decisões técnicas com evidência, testes e documentação.", "Identificar limites, riscos e necessidades de melhoria."], [`Apply the foundations of ${title.en} in a verifiable outcome.`, "Justify technical decisions with evidence, tests and documentation.", "Identify limitations, risks and improvement needs."]),
    competencies: units(["Resolución estructurada de problemas.", "Documentación y reproducibilidad.", "Práctica responsable en el ámbito técnico."], ["Resolução estruturada de problemas.", "Documentação e reprodutibilidade.", "Prática responsável no domínio técnico."], ["Structured problem-solving.", "Documentation and reproducibility.", "Responsible practice in the technical domain."]),
    syllabus: units(["Principios y vocabulario del dominio", "Flujo de trabajo, herramientas y evidencia", "Pruebas, límites y mejora iterativa", "Comunicación técnica y revisión"], ["Princípios e vocabulário do domínio", "Fluxo de trabalho, ferramentas e evidência", "Testes, limites e melhoria iterativa", "Comunicação técnica e revisão"], ["Domain principles and vocabulary", "Workflow, tools and evidence", "Testing, limitations and iterative improvement", "Technical communication and review"]),
    exercises: units(["Documentar un ejemplo mínimo reproducible.", "Resolver un caso guiado y explicar decisiones.", "Realizar una revisión crítica de límites y riesgos."], ["Documentar um exemplo mínimo reprodutível.", "Resolver um caso guiado e explicar decisões.", "Realizar uma revisão crítica de limites e riscos."], ["Document a minimal reproducible example.", "Solve a guided case and explain decisions.", "Conduct a critical review of limitations and risks."]),
    lab: l(`Laboratorio guiado de ${title.es}: práctica documentada con requisitos de hardware publicados y una ruta de menor coste cuando sea viable.`, `Laboratório guiado de ${title.pt}: prática documentada com requisitos de hardware publicados e uma rota de menor custo quando viável.`, `Guided ${title.en} laboratory: documented practice with published hardware requirements and a lower-cost path when viable.`),
    project: l(`Entregar un proyecto de ${title.es} con código o artefactos, README, pruebas apropiadas, fuentes y defensa de decisiones.`, `Entregar um projeto de ${title.pt} com código ou artefactos, README, testes adequados, fontes e defesa de decisões.`, `Deliver a ${title.en} project with code or artifacts, a README, appropriate tests, sources and a decision defense.`),
    aiPolicy: l("La IA se permite como tutor o herramienta declarada. El estudiante debe verificar resultados, citar su uso y no puede delegar la totalidad de una evaluación.", "A IA é permitida como tutora ou ferramenta declarada. O estudante deve verificar resultados, declarar a sua utilização e não pode delegar a totalidade de uma avaliação.", "AI is allowed as a declared tutor or tool. The student must verify results, disclose its use and may not delegate the whole assessment."),
    resources: genericResourcesByTrack[course.track], assessment: sharedAssessment, rubric: sharedRubric,
  };
}

export const getCourse = (code: string) => courses.find(course => course.code === code);
export const getCourseDetail = (code: string) => {
  const course = getCourse(code);
  return detailedCourses[code] ?? (course ? generatedDetail(course) : undefined);
};
