import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { ArrowRight, CheckCircle2, FileDown, FileText, Lightbulb, MessageCircle, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

const interviewPrompts = [
  "Cuéntame una situación en la que aprendiste una herramienta nueva.",
  "¿Cómo explicarías una tarea técnica a una persona que empieza?",
  "¿Qué competencia quieres seguir desarrollando y cómo la practicas?",
];

export default function Employment() {
  const [form, setForm] = useState({ name: "", role: "", summary: "", skills: "", experience: "" });
  const [promptIndex, setPromptIndex] = useState(0);
  const [answer, setAnswer] = useState("");
  const completion = useMemo(() => Object.values(form).filter((value) => value.trim()).length, [form]);
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  return <InstitutionShell>
    <section className="page-hero employment-hero"><p className="eyebrow">Empleo y oportunidades</p><h1>Hacer visible lo que <em>ya sabes hacer.</em></h1><p>Herramientas claras para organizar experiencia, competencias y próximos pasos. No prometemos empleo: te ayudamos a preparar materiales que puedes revisar y adaptar.</p></section>
    <section className="section-wrap employment-layout"><article className="cv-workbench"><div className="workbench-head"><div><p className="eyebrow">Creador de CV</p><h2>Tu historia profesional, con evidencias.</h2></div><span>{completion}/5 secciones</span></div><p>Los datos permanecen en este navegador hasta que decidas imprimir o copiar el documento. No se envían a ningún modelo de IA.</p><div className="cv-fields"><label>Nombre o nombre profesional<input value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Cómo quieres presentarte" /></label><label>Rol o dirección profesional<input value={form.role} onChange={(event) => update("role", event.target.value)} placeholder="Por ejemplo: atención al cliente" /></label><label>Resumen<textarea value={form.summary} onChange={(event) => update("summary", event.target.value)} placeholder="Dos o tres frases sobre tu experiencia, intereses y objetivo." rows={3} /></label><label>Competencias<textarea value={form.skills} onChange={(event) => update("skills", event.target.value)} placeholder="Por ejemplo: comunicación, Excel, atención al público" rows={2} /></label><label>Experiencia o proyecto relevante<textarea value={form.experience} onChange={(event) => update("experience", event.target.value)} placeholder="Describe qué hiciste, con qué herramientas y qué aprendiste." rows={3} /></label></div><div className="cv-actions"><Button className="primary-cta" onClick={() => window.print()}><FileDown size={16} /> Imprimir / guardar como PDF</Button><span><ShieldCheck size={15} /> Tus borradores no se envían automáticamente.</span></div></article>
      <aside className="cv-preview" aria-label="Vista previa del currículum"><div className="cv-preview-top"><FileText size={18} /><span>Vista previa</span></div><h2>{form.name || "Tu nombre"}</h2><h3>{form.role || "Tu dirección profesional"}</h3><div><strong>Perfil</strong><p>{form.summary || "Escribe un resumen para explicar tu experiencia y lo que estás buscando."}</p></div><div><strong>Competencias</strong><p>{form.skills || "Añade competencias que puedas describir con un ejemplo."}</p></div><div><strong>Experiencia o proyecto</strong><p>{form.experience || "Explica una experiencia, tarea o proyecto relevante."}</p></div></aside></section>
    <section className="section-wrap interview-layout"><article className="interview-card"><div><p className="eyebrow">Preparación de entrevista</p><h2>Practica una idea cada vez.</h2><p>Una respuesta útil suele tener contexto, una acción concreta y un aprendizaje. Escribe una primera versión y revísala con calma.</p></div><div className="interview-prompt"><MessageCircle size={20} /><p>{interviewPrompts[promptIndex]}</p><Button variant="outline" className="soft-button" onClick={() => { setPromptIndex((current) => (current + 1) % interviewPrompts.length); setAnswer(""); }}>Otra pregunta <ArrowRight size={15} /></Button></div><textarea aria-label="Tu respuesta de práctica" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Escribe una respuesta breve. Puedes después revisarla con el tutor de aprendizaje." rows={5} /><div className="review-list"><span><CheckCircle2 size={15} /> ¿Dices qué hiciste?</span><span><CheckCircle2 size={15} /> ¿Incluyes un ejemplo real?</span><span><CheckCircle2 size={15} /> ¿Explicas lo que aprendiste?</span></div></article><aside className="employment-guide"><Lightbulb size={22} /><p className="eyebrow">Ruta práctica</p><h3>Preparar no es inventar.</h3><p>El objetivo es reconocer tu experiencia en distintos contextos, documentar lo que puedas sostener y aprender a explicarlo con claridad.</p><a className="text-cta" href="/programas?ruta=everyday">Explorar comunicación aplicada <ArrowRight size={16} /></a></aside></section>
  </InstitutionShell>;
}
