import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { CURRICULUM_LESSONS, getGoal, LANGUAGE_CATALOG } from "@shared/institution";
import { ArrowRight, Award, CheckCircle2, Printer, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

export default function EvidenceRecord() {
  const { user, isAuthenticated, loading } = useAuth();
  const profileQuery = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  if (loading || profileQuery.isLoading) return <InstitutionShell compact><div className="loading-page">Preparando tu constancia…</div></InstitutionShell>;
  if (!isAuthenticated || !profileQuery.data) return <InstitutionShell><section className="guest-dashboard"><p className="eyebrow">Constancia de recorrido</p><h1>Las evidencias necesitan <em>tu propio espacio.</em></h1><p>Inicia sesión para reunir las actividades que completes dentro de Maos Abertas + LinguaForge. No se genera una constancia con datos simulados.</p><div><Button className="primary-cta" onClick={() => startLogin()}>Entrar y conservar evidencias <ArrowRight size={16} /></Button><Link href="/programas" className="text-cta">Ver programas <ArrowRight size={16} /></Link></div></section></InstitutionShell>;
  const profile = profileQuery.data;
  const language = LANGUAGE_CATALOG.find((item) => item.code === profile.targetLanguageCode);
  const goal = getGoal(profile.learningGoal as Parameters<typeof getGoal>[0]);
  const completed = CURRICULUM_LESSONS.filter((lesson) => profile.completedLessonIds.includes(lesson.id));
  const completedProjects = profile.projectSubmissions.filter((submission) => submission.status === "completed");
  return <InstitutionShell compact><section className="evidence-page"><div className="evidence-toolbar no-print"><Link href="/mi-espacio" className="back-link">← Volver a mi espacio</Link><Button className="primary-cta" onClick={() => window.print()}><Printer size={16} /> Imprimir / guardar como PDF</Button></div><article className="evidence-sheet"><div className="evidence-mark"><span className="brand-seal">M</span><div><p>Maos Abertas + LinguaForge</p><small>Institución digital abierta</small></div><Award size={26} /></div><div className="evidence-rule" /><p className="eyebrow">Registro personal de aprendizaje</p><h1>Constancia de <em>recorrido.</em></h1><p className="evidence-intro">Este documento registra actividades realmente marcadas como completadas en la plataforma por <strong>{user?.name ?? "la persona estudiante"}</strong>. Es una evidencia personal de recorrido, no un título, diploma, acreditación ni certificación oficial.</p><div className="evidence-summary"><div><span>Facultad de entrada</span><strong>{goal?.title ?? profile.learningGoal}</strong></div><div><span>Idioma de estudio</span><strong>{language?.name ?? profile.targetLanguageCode.toUpperCase()}</strong></div><div><span>Actividades registradas</span><strong>{completed.length + completedProjects.length}</strong></div></div>{completed.length > 0 || completedProjects.length > 0 ? <div className="evidence-list"><p className="eyebrow">Evidencias registradas</p>{completed.map((lesson) => <article key={lesson.id}><CheckCircle2 size={17} /><div><strong>{lesson.title}</strong><span>{getGoal(lesson.goalId)?.shortTitle} · {lesson.level} · {lesson.minutes} min</span></div></article>)}{completedProjects.map((submission) => <article key={submission.id}><CheckCircle2 size={17} /><div><strong>Proyecto: {submission.projectId.replace("project-", "").replaceAll("-", " ")}</strong><span>Proyecto de aprendizaje registrado personalmente</span></div></article>)}</div> : <div className="evidence-empty"><ShieldCheck size={20} /><div><strong>Aún no hay actividades registradas.</strong><p>Completa una lección o registra un proyecto para crear una constancia basada en una evidencia real. La plataforma no inventa logros.</p><Link href="/programas">Explorar una facultad <ArrowRight size={15} /></Link></div></div>}<div className="evidence-footer"><span>Generado desde el perfil personal el {new Intl.DateTimeFormat("es-ES", { dateStyle: "long" }).format(new Date())}.</span><span>maos abertas + linguaforge · registro no oficial</span></div></article></section></InstitutionShell>;
}
