import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { LAB_CATALOG, detectLanguageSignal, lookupLocalGlossary } from "@shared/content";
import { ArrowRight, BookText, CheckCircle2, Clock3, Languages, Pause, Play, RotateCcw, Sparkles, TimerReset, WandSparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

function displayTime(totalSeconds: number) {
  const minutes = Math.floor(totalSeconds / 60).toString().padStart(2, "0");
  const seconds = (totalSeconds % 60).toString().padStart(2, "0");
  return `${minutes}:${seconds}`;
}

export default function Labs() {
  const [activeLab, setActiveLab] = useState("language-signal");
  const [text, setText] = useState("");
  const [goal, setGoal] = useState("");
  const [context, setContext] = useState("");
  const [format, setFormat] = useState("Una explicación breve con un ejemplo");
  const [minutes, setMinutes] = useState(10);
  const [remaining, setRemaining] = useState(600);
  const [running, setRunning] = useState(false);
  const [glossarySource, setGlossarySource] = useState<"es" | "en" | "pt">("es");
  const [glossaryQuery, setGlossaryQuery] = useState("hola");
  const lab = LAB_CATALOG.find((item) => item.id === activeLab) ?? LAB_CATALOG[0];
  const languageSignal = useMemo(() => detectLanguageSignal(text), [text]);
  const glossaryResult = useMemo(() => lookupLocalGlossary(glossaryQuery, glossarySource), [glossaryQuery, glossarySource]);
  const structuredPrompt = goal.trim() ? `Objetivo: ${goal.trim()}\nContexto: ${context.trim() || "No indicado"}\nIdioma de respuesta: Español\nFormato solicitado: ${format}\nLímite: Explica lo que no sepas y propone cómo verificarlo.` : "Completa un objetivo para construir una petición estructurada.";
  useEffect(() => { if (!running) setRemaining(minutes * 60); }, [minutes, running]);
  useEffect(() => { if (!running || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [remaining, running]);
  useEffect(() => { if (remaining === 0) setRunning(false); }, [remaining]);
  return <InstitutionShell>
    <section className="page-hero labs-hero"><p className="eyebrow">Laboratorios abiertos</p><h1>Probar una idea. <em>Entender su límite.</em></h1><p>Espacios pequeños y transparentes para explorar lenguaje, IA, voz y hábitos de aprendizaje. Cada laboratorio indica qué funciona hoy, cómo funciona y qué no promete.</p></section>
    <section className="section-wrap lab-layout"><aside className="lab-index"><div className="demo-label">Modo demostración</div>{LAB_CATALOG.map((item) => <button type="button" className={activeLab === item.id ? "active" : ""} onClick={() => setActiveLab(item.id)} key={item.id}><span className={`status-dot ${item.status}`} /><strong>{item.title}</strong><small>{item.status}</small></button>)}</aside>
      <article className="lab-stage"><div className="lab-stage-head"><div><p className="eyebrow">{lab.status}</p><h2>{lab.title}</h2></div><span className={`lab-status ${lab.status}`}>{lab.status}</span></div><p className="lab-purpose">{lab.purpose}</p>
        {activeLab === "language-signal" && <div className="lab-tool language-signal-tool"><div className="tool-intro"><Languages size={22} /><div><strong>Detector local de señales</strong><p>Escribe una frase. El análisis ocurre en tu navegador y no usa un proveedor de IA.</p></div></div><textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Escribe una frase corta en cualquier idioma…" rows={5} /><div className="signal-result"><span className={`confidence ${languageSignal.confidence}`}>{languageSignal.confidence} confianza</span><h3>{languageSignal.language}</h3><p>{languageSignal.explanation}</p></div></div>}
        {activeLab === "language-compare" && <div className="lab-tool glossary-tool"><div className="tool-intro"><BookText size={22} /><div><strong>Microglosario LinguaForge</strong><p>Busca una palabra exacta del glosario local. La comparación es visible, limitada y no sustituye una traducción profesional.</p></div></div><div className="glossary-controls"><label>Idioma de búsqueda<select value={glossarySource} onChange={(event) => setGlossarySource(event.target.value as "es" | "en" | "pt")}><option value="es">Español</option><option value="en">English</option><option value="pt">Português</option></select></label><label>Palabra<input value={glossaryQuery} onChange={(event) => setGlossaryQuery(event.target.value)} placeholder="Por ejemplo: fuente" /></label></div>{glossaryResult ? <div className="glossary-result"><div><span>ES</span><strong>{glossaryResult.translations.es}</strong></div><div><span>EN</span><strong>{glossaryResult.translations.en}</strong></div><div><span>PT</span><strong>{glossaryResult.translations.pt}</strong></div><p><b>{glossaryResult.domain}</b> · {glossaryResult.note}</p></div> : <div className="glossary-empty"><strong>No está en este microglosario local.</strong><p>Prueba con: hola, ayuda, cuenta, contraseña, fuente o práctica. La arquitectura está preparada para ampliar diccionarios y proveedores sin presentar resultados inexistentes.</p></div>}</div>}
        {activeLab === "prompt-studio" && <div className="lab-tool prompt-tool"><div className="tool-intro"><WandSparkles size={22} /><div><strong>De intención a petición</strong><p>Una plantilla local que hace visible lo que una herramienta necesita saber para responder mejor.</p></div></div><div className="prompt-fields"><label>¿Qué quieres conseguir?<textarea value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="Por ejemplo: entender una palabra técnica" rows={2} /></label><label>¿Qué contexto ayuda a comprenderte?<textarea value={context} onChange={(event) => setContext(event.target.value)} placeholder="Por ejemplo: estudio inglés en nivel A2" rows={2} /></label><label>¿Cómo quieres la respuesta?<select value={format} onChange={(event) => setFormat(event.target.value)}><option>Una explicación breve con un ejemplo</option><option>Una práctica de cinco minutos</option><option>Una lista de comprobación</option><option>Una comparación en dos idiomas</option></select></label></div><pre className="prompt-output">{structuredPrompt}</pre></div>}
        {activeLab === "learning-focus" && <div className="lab-tool focus-tool"><div className="tool-intro"><Clock3 size={22} /><div><strong>Una sesión, una intención</strong><p>Un temporizador local para reducir interrupciones y cerrar cada práctica con una reflexión propia.</p></div></div><div className="focus-clock"><span>{displayTime(remaining)}</span><small>{running ? "Sesión en marcha" : remaining === 0 ? "Sesión finalizada" : "Sesión preparada"}</small></div><div className="time-controls">{[5, 10, 20].map((option) => <button type="button" className={minutes === option ? "active" : ""} onClick={() => { setMinutes(option); setRunning(false); }} key={option}>{option} min</button>)}</div><div className="focus-actions"> <Button className="primary-cta" onClick={() => setRunning((value) => !value)}>{running ? <Pause size={16} /> : <Play size={16} />}{running ? "Pausar" : "Iniciar sesión"}</Button><Button variant="outline" className="soft-button" onClick={() => { setRunning(false); setRemaining(minutes * 60); }}><TimerReset size={16} /> Reiniciar</Button></div></div>}
        {activeLab === "voice-lab" && <div className="lab-tool unavailable-tool"><Sparkles size={25} /><h3>La práctica oral está integrada en las lecciones.</h3><p>El laboratorio explica su alcance; para probarlo, abre una actividad y selecciona “Practicar respuesta oral”.</p><a className="text-cta" href="/lecciones/everyday-a1-introductions">Abrir práctica oral <ArrowRight size={16} /></a></div>}
        {(activeLab === "semantic-library" || activeLab === "open-voice-adapter") && <div className="lab-tool unavailable-tool"><Sparkles size={25} /><h3>Esta capacidad está en investigación.</h3><p>La interfaz no simula que existe un servicio conectado. Consulta la arquitectura técnica para ver los contratos, controles y requisitos de integración.</p><a className="text-cta" href="https://github.com/belentani7/Maod-abertas#documentaci%C3%B3n-complementaria" target="_blank" rel="noreferrer">Ver documentación técnica <ArrowRight size={16} /></a></div>}
        <div className="lab-disclosure"><div><strong>Tecnología</strong><span>{lab.technology}</span></div><div><strong>Límite</strong><span>{lab.limitation}</span></div><div><strong>Servicios externos</strong><span>{lab.externalService ? "Sí, indicado antes de enviar datos." : "No para esta interacción."}</span></div></div>
      </article></section>
    <section className="section-wrap labs-principles"><article><CheckCircle2 size={19} /><h3>Estado visible</h3><p>Operativo, demostración o diseño no son etiquetas de marketing: determinan qué puedes esperar.</p></article><article><Sparkles size={19} /><h3>Sin magia negra</h3><p>Los resultados locales se presentan como reglas; los servicios de IA se nombran y acotan.</p></article><article><RotateCcw size={19} /><h3>Control de la persona</h3><p>Los temporizadores, borradores y prácticas se pueden pausar, repetir o abandonar sin penalización.</p></article></section>
  </InstitutionShell>;
}
