import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { getGoal, INSTITUTION_COMPETENCIES, LANGUAGE_CATALOG, LEARNING_GOALS, recommendInstitutionalPath, type CompetencySignals, type LearningGoalId } from "@shared/institution";
import { ArrowRight, CheckCircle2, ChevronLeft, Gauge, Sparkles } from "lucide-react";
import { useState } from "react";
import { Link, useLocation, useSearch } from "wouter";

export default function Onboarding() {
  const { isAuthenticated } = useAuth();
  const [, navigate] = useLocation();
  const query = new URLSearchParams(useSearch());
  const [step, setStep] = useState(0);
  const [nativeLanguageCode, setNativeLanguageCode] = useState("es");
  const [targetLanguageCode, setTargetLanguageCode] = useState(query.get("estudio") ?? "en");
  const [learningGoal, setLearningGoal] = useState<LearningGoalId>("everyday");
  const [scores, setScores] = useState({ comprehension: 25, expression: 25, interaction: 25 });
  const [competencies, setCompetencies] = useState<CompetencySignals>({ communication: 50, digital: 50, creation: 50, critical: 50, pathway: 50 });
  const completeDiagnostic = trpc.diagnostic.complete.useMutation({ onSuccess: () => navigate("/mi-espacio") });
  const recommended = scores.comprehension + scores.expression + scores.interaction >= 240 ? "C1" : scores.comprehension + scores.expression + scores.interaction >= 180 ? "B2" : scores.comprehension + scores.expression + scores.interaction >= 135 ? "B1" : scores.comprehension + scores.expression + scores.interaction >= 90 ? "A2" : "A1";
  const institutionalRecommendation = recommendInstitutionalPath(competencies);
  const companion = getGoal(institutionalRecommendation.companionGoal);
  const submit = () => { localStorage.setItem("maos-learning-draft", JSON.stringify({ nativeLanguageCode, targetLanguageCode, learningGoal, recommended, competencies, companionGoal: institutionalRecommendation.companionGoal })); if (isAuthenticated) completeDiagnostic.mutate({ targetLanguageCode, learningGoal, scores, competencies }); else setStep(3); };
  return <InstitutionShell compact>
    <section className="onboarding-page"><Link href="/" className="back-link"><ChevronLeft size={16} /> Volver al inicio</Link><div className="onboarding-top"><p className="eyebrow">Diseña tu recorrido</p><span>Paso {Math.min(step + 1, 3)} de 3</span></div><div className="onboarding-progress"><i style={{ width: `${((Math.min(step, 2) + 1) / 3) * 100}%` }} /></div>
      {step === 0 && <div className="onboarding-card"><div className="step-icon"><Sparkles size={23} /></div><p className="eyebrow">Tu contexto de aprendizaje</p><h1>Empecemos por las lenguas que ya te acompañan.</h1><p>Elegir un idioma de apoyo y uno de estudio permite adaptar instrucciones, ejemplos y tutorías, incluso si tu primera facultad es ciudadanía digital, tecnología, programación, IA o trayectorias profesionales.</p><div className="field-row"><label>Idioma de apoyo<select value={nativeLanguageCode} onChange={(event) => setNativeLanguageCode(event.target.value)}>{LANGUAGE_CATALOG.map((item) => <option key={item.code} value={item.code}>{item.name} — {item.nativeName}</option>)}</select></label><label>Idioma de estudio<select value={targetLanguageCode} onChange={(event) => setTargetLanguageCode(event.target.value)}>{LANGUAGE_CATALOG.map((item) => <option key={item.code} value={item.code}>{item.name} — {item.nativeName}</option>)}</select></label></div><Button className="primary-cta wide" onClick={() => setStep(1)}>Continuar <ArrowRight size={17} /></Button></div>}
      {step === 1 && <div className="onboarding-card"><div className="step-icon"><Gauge size={23} /></div><p className="eyebrow">Tu objetivo</p><h1>¿Qué quieres poder hacer primero?</h1><p>Elige una de las facultades de entrada. Después proponemos una competencia complementaria; puedes cambiar tu ruta en cualquier momento.</p><div className="goal-picker">{LEARNING_GOALS.map((goal) => <button type="button" key={goal.id} className={learningGoal === goal.id ? "picked" : ""} onClick={() => setLearningGoal(goal.id)}><span>{learningGoal === goal.id && <CheckCircle2 size={16} />}</span><strong>{goal.shortTitle}</strong><small>{goal.description}</small></button>)}</div><div className="dual-actions"><Button variant="outline" onClick={() => setStep(0)}>Atrás</Button><Button className="primary-cta" onClick={() => setStep(2)}>Continuar <ArrowRight size={17} /></Button></div></div>}
      {step === 2 && <div className="onboarding-card"><div className="step-icon"><Gauge size={23} /></div><p className="eyebrow">Diagnóstico orientativo</p><h1>¿Con qué confianza empiezas hoy?</h1><p>Esta orientación no es una prueba oficial, ni un perfil psicológico, ni limita tu acceso. Solo propone un nivel lingüístico y un complemento de aprendizaje que puedes cambiar.</p><div className="score-fields">{([{ key: "comprehension", label: "Comprender instrucciones y textos" }, { key: "expression", label: "Expresarte por escrito u oralmente" }, { key: "interaction", label: "Mantener una interacción breve" }] as const).map((item) => <label key={item.key}><span>{item.label}<b>{scores[item.key]} / 100</b></span><input type="range" min="0" max="100" step="5" value={scores[item.key]} onChange={(event) => setScores({ ...scores, [item.key]: Number(event.target.value) })} /></label>)}</div><div className="competency-diagnostic"><p className="eyebrow">Competencias transversales</p>{INSTITUTION_COMPETENCIES.map((item) => <label key={item.id}><span>{item.title}<b>{competencies[item.id]} / 100</b></span><small>{item.description}</small><input type="range" min="0" max="100" step="5" value={competencies[item.id]} onChange={(event) => setCompetencies({ ...competencies, [item.id]: Number(event.target.value) })} /></label>)}</div><div className="recommendation-box"><span>Nivel lingüístico orientativo</span><strong>{recommended}</strong><p>Complemento propuesto: <b>{companion?.shortTitle ?? "Una facultad de la institución"}</b>. Podrás modificarlo desde tu espacio de aprendizaje.</p></div><div className="dual-actions"><Button variant="outline" onClick={() => setStep(1)}>Atrás</Button><Button className="primary-cta" disabled={completeDiagnostic.isPending} onClick={submit}>{isAuthenticated ? "Guardar mi recorrido" : "Ver mi recorrido"} <ArrowRight size={17} /></Button></div></div>}
      {step === 3 && <div className="onboarding-card finish-card"><CheckCircle2 size={43} /><p className="eyebrow">Tu propuesta está lista</p><h1>Tu punto de partida lingüístico es <em>{recommended}.</em></h1><p>Tu facultad complementaria recomendada es <b>{companion?.shortTitle ?? "la que tú elijas"}</b>. Inicia sesión para guardar avance, conversar con el tutor y conservar tus prácticas orales.</p><div className="finish-actions"><Button className="primary-cta" onClick={() => startLogin()}>Entrar y guardar mi recorrido <ArrowRight size={17} /></Button><Link href="/programas" className="text-cta">Explorar facultades <ArrowRight size={16} /></Link></div></div>}
    </section>
  </InstitutionShell>;
}
