"""Conteúdo pedagógico real — trilha Informática (40 módulos)."""

INFORMATICA = [
    ("info-ligar", "Ligar e desligar o computador", "Botão de energia e tela inicial.", [
        ("explanation", "Entender", "O botão de energia liga e desliga a máquina. Ligar é rápido, mas desligar deve ser feito pelo menu, para o computador fechar os programas com segurança."),
        ("example", "Ver um exemplo", "No Windows, clique no menu Iniciar e escolha Desligar. Puxar a tomada da parede pode corromper arquivos."),
        ("practice", "Praticar", "Ligue o computador, espere a tela inicial aparecer e depois desligue corretamente pelo menu."),
        ("check", "Verificar", "Você desligou pelo menu, e não pela tomada? Se apareceu a mensagem 'Fechando...', fez certo."),
        ("next", "Próximo passo", "Com a máquina ligada, o próximo passo é aprender a apontar e clicar."),
    ]),
    ("info-mouse", "Usar o mouse", "Clicar, arrastar e rolar.", [
        ("explanation", "Entender", "O mouse move a seta na tela. O botão esquerdo seleciona e abre; o direito mostra opções; a rodinha rola a página para cima e para baixo."),
        ("example", "Ver um exemplo", "Um clique seleciona um arquivo; dois cliques rápidos o abrem. Segurar o botão esquerdo e mover arrasta o item."),
        ("practice", "Praticar", "Abra uma pasta, selecione um arquivo com um clique, abra com dois cliques, role a lista e clique com o botão direito."),
        ("check", "Verificar", "Se a seta não se move, o mouse está mal encaixado ou sem bateria. Teste em uma superfície lisa."),
        ("next", "Próximo passo", "Depois do mouse, o teclado dá muito mais velocidade."),
    ]),
    ("info-teclado", "Conhecer o teclado", "Letras, números, espaço e Enter.", [
        ("explanation", "Entender", "O teclado tem letras, números, a barra de espaço e teclas de ação. Enter confirma, Backspace apaga o que está antes e Shift escreve maiúsculas."),
        ("example", "Ver um exemplo", "Para escrever uma letra maiúscula, segure Shift e aperte a letra. Para apagar, use Backspace, que apaga da direita para a esquerda."),
        ("practice", "Praticar", "Abra um editor de texto e escreva seu nome completo, usando maiúsculas no início. Apague e reescreva."),
        ("check", "Verificar", "Se saiu tudo em maiúscula, a tecla Caps Lock está ligada. Aperte-a uma vez para desligar."),
        ("next", "Próximo passo", "Com mouse e teclado dominados, você navega pelo celular com facilidade."),
    ]),
    ("info-celular", "Navegar no celular", "Tocar, deslizar, abrir apps.", [
        ("explanation", "Entender", "No celular tudo se faz com o dedo: tocar abre, deslizar rola, segurar mostra opções e pinçar com dois dedos dá zoom."),
        ("example", "Ver um exemplo", "Para rolar o feed, deslize o dedo de baixo para cima. Para voltar, deslize da borda esquerda para a direita."),
        ("practice", "Praticar", "Abra três aplicativos, navegue entre eles e volte para a tela inicial. Depois gire o celular de lado."),
        ("check", "Verificar", "Se algum app não responde, feche-o e abra de novo. Reiniciar o aparelho resolve a maioria dos travamentos."),
        ("next", "Próximo passo", "Saber navegar abre a porta para a internet e a comunicação."),
    ]),
    ("info-internet", "O que é a internet", "Como a rede conecta pessoas.", [
        ("explanation", "Entender", "A internet é uma rede mundial de computadores conectados. Quando você acessa um site, seu aparelho pede a informação a um servidor e recebe a página de volta."),
        ("example", "Ver um exemplo", "Enviar uma mensagem é como mandar uma carta eletrônica: sai do seu aparelho, passa por vários pontos da rede e chega ao destino em segundos."),
        ("practice", "Praticar", "Abra o navegador e acesse um site de notícias. Observe o endereço na barra superior e o cadeado de segurança."),
        ("check", "Verificar", "Se a página não abre, verifique se o Wi-Fi está ligado. Sem conexão, nada carrega."),
        ("next", "Próximo passo", "Com internet, você pode pesquisar qualquer assunto."),
    ]),
    ("info-busca", "Pesquisar na internet", "Encontrar o que você precisa.", [
        ("explanation", "Entender", "Um buscador procura palavras na internet e devolve uma lista de resultados. Quanto mais específicas as palavras, melhores os resultados."),
        ("example", "Ver um exemplo", "Buscar 'conta de luz' traz resultados genéricos. Buscar 'como ler conta de luz vencimento' traz respostas exatas."),
        ("practice", "Praticar", "Pesquise 'como tirar segunda via da conta de luz'. Abra os três primeiros resultados e compare as respostas."),
        ("check", "Verificar", "Desconfie de anúncios no topo e de sites estranhos. Prefira resultados de órgãos oficiais e empresas conhecidas."),
        ("next", "Próximo passo", "Pesquisar bem é a base para usar e-mail e serviços online."),
    ]),
    ("info-email", "Criar e usar um e-mail", "Escrever, enviar e receber.", [
        ("explanation", "Entender", "E-mail é uma mensagem eletrônica com endereço. O endereço tem o símbolo @, que separa o seu nome do provedor, como nome@gmail.com."),
        ("example", "Ver um exemplo", "Para enviar, preencha o campo Para com o endereço, o Assunto com o tema e o corpo com a mensagem. Depois clique em Enviar."),
        ("practice", "Praticar", "Crie um e-mail para você mesmo com assunto 'Teste' e escreva duas linhas. Envie e confira se chegou na caixa de entrada."),
        ("check", "Verificar", "Se não chegou, olhe na pasta Spam. Muitas mensagens caem lá por engano."),
        ("next", "Próximo passo", "O e-mail é a chave para criar contas em outros serviços."),
    ]),
    ("info-senha", "Criar uma senha segura", "Proteger suas contas.", [
        ("explanation", "Entender", "Uma senha boa é longa e mistura letras maiúsculas, minúsculas, números e símbolos. Evite datas de nascimento e nomes de parentes."),
        ("example", "Ver um exemplo", "'123456' é péssima: existe em milhões de contas. 'Cafe-com-Leite#72' é longa, tem símbolos e é fácil de lembrar."),
        ("practice", "Praticar", "Crie uma frase-senha com quatro palavras e um número, e teste sua força. Não use a mesma senha em dois serviços."),
        ("check", "Verificar", "Nunca anote a senha em papel colado no monitor. Se precisar anotar, guarde em local trancado."),
        ("next", "Próximo passo", "Com senhas fortes, você pode ativar a verificação em duas etapas."),
    ]),
    ("info-whatsapp", "Usar o WhatsApp", "Mensagens, fotos e áudios.", [
        ("explanation", "Entender", "O WhatsApp envia mensagens de texto, áudio, foto e vídeo pela internet. Um tique significa enviado; dois tiques, entregue; dois azuis, lido."),
        ("example", "Ver um exemplo", "Para mandar áudio, segure o microfone e fale. Solte para enviar; arraste para o lado para cancelar."),
        ("practice", "Praticar", "Envie uma mensagem de texto, um áudio curto e uma foto para um contato de confiança."),
        ("check", "Verificar", "Desconfie de mensagens pedindo dinheiro com urgência, mesmo de contatos conhecidos. Confirme por ligação."),
        ("next", "Próximo passo", "Além de conversar, você pode guardar arquivos e fazer chamadas de vídeo."),
    ]),
    ("info-fotos", "Organizar fotos", "Pastas e liberar espaço.", [
        ("explanation", "Entender", "Fotos ocupam bastante espaço. Organizar por pastas e apagar as repetidas ou tremidas mantém o celular rápido e libera memória."),
        ("example", "Ver um exemplo", "Crie pastas como 'Família', 'Documentos' e 'Viagens'. Assim você acha uma foto em segundos, em vez de rolar milhares."),
        ("practice", "Praticar", "Escolha 30 fotos, separe em duas pastas e apague as que ficaram fora de foco."),
        ("check", "Verificar", "Antes de apagar em massa, confira se há backup na nuvem. Foto apagada sem cópia não volta."),
        ("next", "Próximo passo", "Guardar na nuvem evita perder tudo se o aparelho quebrar."),
    ]),
    ("info-pix", "Fazer e receber Pix", "Transferências com segurança.", [
        ("explanation", "Entender", "Pix é transferência instantânea entre contas, a qualquer hora. Usa uma chave: CPF, telefone, e-mail ou chave aleatória."),
        ("example", "Ver um exemplo", "Para receber, mostre sua chave ou o QR Code. Para enviar, digite a chave, confira o nome do destinatário e confirme."),
        ("practice", "Praticar", "No app do banco, localize sua chave Pix e copie. Depois simule uma transferência de R$ 1,00 sem confirmar."),
        ("check", "Verificar", "Sempre confira o nome e o CPF antes de confirmar. Golpistas usam chaves parecidas com as de lojas conhecidas."),
        ("next", "Próximo passo", "Com Pix, você também pode pagar contas por QR Code."),
    ]),
    ("info-docs", "Usar um editor de texto", "Escrever, salvar e compartilhar.", [
        ("explanation", "Entender", "Um editor de texto cria documentos com formatação. O trabalho precisa ser salvo em arquivo, senão se perde ao fechar o programa."),
        ("example", "Ver um exemplo", "No Google Docs ou no Word, escreva o texto e use Ctrl+B para negrito e Ctrl+S para salvar. O nome do arquivo aparece no topo."),
        ("practice", "Praticar", "Escreva um texto de cinco linhas sobre seu dia, aplique negrito em uma palavra e salve com o nome 'meu-texto'."),
        ("check", "Verificar", "Feche e abra o arquivo de novo. Se o texto está lá, você salvou corretamente."),
        ("next", "Próximo passo", "Do texto simples você passa para planilhas e currículos."),
    ]),
    ("info-planilha", "Planilha simples", "Organizar gastos em colunas.", [
        ("explanation", "Entender", "Uma planilha organiza dados em linhas e colunas e faz contas automaticamente. Cada retângulo é uma célula, identificada por letra e número, como A1."),
        ("example", "Ver um exemplo", "Na coluna A escreva o nome do gasto, na B o valor. Na última linha, use =SOMA(B2:B10) para o total."),
        ("practice", "Praticar", "Monte uma planilha com cinco gastos do mês: descrição, valor e o total na última linha."),
        ("check", "Verificar", "Confira o total somando na calculadora. Se bater com a planilha, a fórmula está correta."),
        ("next", "Próximo passo", "Com planilhas, o orçamento da casa fica sob controle."),
    ]),
    ("info-golpes", "Reconhecer golpes online", "Links falsos e como se proteger.", [
        ("explanation", "Entender", "Golpes chegam por mensagem, e-mail ou site falso e pedem dados, dinheiro ou urgência. A pressa é o principal sinal de alerta."),
        ("example", "Ver um exemplo", "'Seu prêmio expira em 10 minutos, clique aqui' é golpe clássico. Bancos não pedem senha nem pedem transferência por mensagem."),
        ("practice", "Praticar", "Analise três mensagens suspeitas: veja o remetente, o link e os erros de português. Marque as que parecem falsas."),
        ("check", "Verificar", "Nunca clique no link. Abra o app oficial do banco ou ligue para o número do cartão e confirme."),
        ("next", "Próximo passo", "Reconhecer golpes protege seu dinheiro e seus dados."),
    ]),
    ("info-curriculo", "Fazer um currículo digital", "Modelo pronto para enviar.", [
        ("explanation", "Entender", "O currículo mostra seus dados, sua experiência e suas habilidades em uma página, na ordem do mais importante para o menos."),
        ("example", "Ver um exemplo", "Comece com nome e contato, siga com experiência (o que fez e onde), formação e habilidades. Duas páginas no máximo."),
        ("practice", "Praticar", "Escreva seu currículo em um editor de texto e salve em PDF. Peça para alguém revisar a ortografia."),
        ("check", "Verificar", "Confira telefone e e-mail antes de enviar. Erro de contato já elimina candidaturas."),
        ("next", "Próximo passo", "Com o currículo pronto, você pode se candidatar pela internet."),
    ]),
    ("info-arquivos", "Guardar e encontrar arquivos", "Pastas, nomes e buscas.", [
        ("explanation", "Entender", "Arquivos ficam dentro de pastas. Nomes claros e uma organização simples evitam perder documentos importantes."),
        ("example", "Ver um exemplo", "Crie uma pasta 'Documentos' com subpastas 'Contas', 'Saúde' e 'Trabalho'. Nomeie os arquivos com data: '2026-03-conta-luz'."),
        ("practice", "Praticar", "Organize 15 arquivos em três pastas com nomes claros. Use a busca do sistema para achar um deles."),
        ("check", "Verificar", "Se você levou mais de um minuto para achar um arquivo, a organização ainda precisa melhorar."),
        ("next", "Próximo passo", "Boa organização facilita fazer backup e encontrar qualquer arquivo rápido."),
    ]),
    ("info-usb", "Usar um pendrive", "Copiar e ejetar com segurança.", [
        ("explanation", "Entender", "O pendrive é uma memória portátil que conecta na porta USB. Ele aparece como uma unidade no computador, pronta para receber arquivos."),
        ("example", "Ver um exemplo", "Conecte o pendrive, abra a pasta dele, arraste o arquivo para dentro e espere a cópia terminar antes de retirar."),
        ("practice", "Praticar", "Copie um documento para o pendrive, confira se abriu no destino e depois ejete com segurança."),
        ("check", "Verificar", "Se aparecer 'não é possível ejetar', algum arquivo ainda está aberto. Feche-o e tente de novo."),
        ("next", "Próximo passo", "O pendrive serve para transportar arquivos e imprimir em outro lugar."),
    ]),
    ("info-impressora", "Imprimir um documento", "Escolher impressora e papel.", [
        ("explanation", "Entender", "Para imprimir, o computador precisa estar conectado à impressora, por cabo ou Wi-Fi, e o papel precisa estar carregado."),
        ("example", "Ver um exemplo", "Abra o documento, use Ctrl+P, escolha a impressora, defina as páginas e clique em Imprimir. A fila mostra o andamento."),
        ("practice", "Praticar", "Imprima apenas a primeira página de um documento, em preto e branco, para economizar tinta."),
        ("check", "Verificar", "Se nada sair, confira se há papel, se a impressora está ligada e se o documento não ficou preso na fila."),
        ("next", "Próximo passo", "Você também pode salvar em PDF em vez de gastar papel."),
    ]),
    ("info-videochamada", "Fazer uma videochamada", "Câmera, microfone e link.", [
        ("explanation", "Entender", "A videochamada transmite imagem e som pela internet. Precisa de conexão estável, câmera e microfone liberados."),
        ("example", "Ver um exemplo", "No Google Meet, o organizador envia um link. Ao entrar, você escolhe permitir câmera e microfone e pode silenciar quando não estiver falando."),
        ("practice", "Praticar", "Faça uma chamada de teste com alguém por 2 minutos. Teste ligar e desligar o microfone."),
        ("check", "Verificar", "Se a imagem trava, aproxime-se do roteador ou reduza a qualidade do vídeo. Silencie o microfone quando não estiver falando."),
        ("next", "Próximo passo", "Videochamadas resolvem consultas, entrevistas e aulas a distância."),
    ]),
    ("info-mapa", "Usar mapas e GPS", "Encontrar endereços e rotas.", [
        ("explanation", "Entender", "O GPS usa satélites para saber onde você está. O aplicativo de mapas calcula a rota a pé, de carro ou de transporte público."),
        ("example", "Ver um exemplo", "Digite o endereço de destino e escolha o meio de transporte. O app mostra o tempo estimado e a rota passo a passo."),
        ("practice", "Praticar", "Busque o trajeto da sua casa até o posto de saúde mais próximo e veja quanto tempo leva a pé."),
        ("check", "Verificar", "Ative a localização do celular se o mapa não encontrar você. Sem GPS, a rota não funciona."),
        ("next", "Próximo passo", "Mapas ajudam a chegar a entrevistas e consultas no horário."),
    ]),
    ("info-compras", "Comprar online com segurança", "Sites confiáveis e pagamento.", [
        ("explanation", "Entender", "Comprar online exige conferir se o site é confiável, se o preço é realista e se existe política de troca. O endereço deve começar com https e mostrar o cadeado."),
        ("example", "Ver um exemplo", "Um celular novo por R$ 200 em site desconhecido é golpe. Prefira lojas conhecidas e pague com cartão virtual ou Pix em site oficial."),
        ("practice", "Praticar", "Pesquise o nome da loja mais 'reclamações' antes de comprar. Leia três avaliações de outros compradores."),
        ("check", "Verificar", "Guarde o comprovante e o número do pedido. Sem eles, a reclamação fica difícil."),
        ("next", "Próximo passo", "Comprar com segurança é a mesma lógica de usar o app do banco."),
    ]),
    ("info-banco", "Usar o app do banco", "Saldo, extrato e pagamentos.", [
        ("explanation", "Entender", "O aplicativo do banco mostra saldo, extrato e permite pagar contas e transferir. O acesso usa senha e, de preferência, verificação em duas etapas."),
        ("example", "Ver um exemplo", "Para pagar uma conta, use a câmera para ler o código de barras, confira valor e vencimento e confirme com a senha."),
        ("practice", "Praticar", "Abra o app, localize o extrato do mês e identifique três movimentações. Não faça nenhuma transferência."),
        ("check", "Verificar", "Nunca acesse o banco por link recebido em mensagem. Abra sempre o aplicativo oficial."),
        ("next", "Próximo passo", "Com o app dominado, você pode cadastrar contas para pagamento automático."),
    ]),
    ("info-sus", "Usar serviços públicos online", "Agendamentos e documentos.", [
        ("explanation", "Entender", "Muitos serviços públicos têm portal ou aplicativo: agendar consulta, emitir documento e acompanhar pedidos. O acesso costuma pedir CPF e senha do gov.br."),
        ("example", "Ver um exemplo", "No aplicativo do SUS ou no portal gov.br, você agenda consulta, vê o histórico e baixa o cartão de vacinação."),
        ("practice", "Praticar", "Crie ou recupere sua conta gov.br e localize o serviço de agendamento de consulta."),
        ("check", "Verificar", "Confira se o endereço termina em gov.br antes de digitar seus dados. Sites parecidos são armadilhas comuns."),
        ("next", "Próximo passo", "Serviços online economizam filas e deslocamento."),
    ]),
    ("info-nuvem", "Guardar na nuvem", "Acessar arquivos de qualquer lugar.", [
        ("explanation", "Entender", "A nuvem guarda seus arquivos em servidores na internet. Assim você acessa de qualquer aparelho e não perde tudo se o celular quebrar."),
        ("example", "Ver um exemplo", "Google Drive e OneDrive oferecem espaço gratuito. O arquivo enviado fica disponível no celular e no computador ao mesmo tempo."),
        ("practice", "Praticar", "Envie um documento para a nuvem, abra-o em outro aparelho e confirme que o conteúdo está igual."),
        ("check", "Verificar", "Documentos com dados pessoais devem ficar em pasta privada. Confira quem tem permissão de ver."),
        ("next", "Próximo passo", "A nuvem é a forma mais simples de fazer backup."),
    ]),
    ("info-wifi", "Conectar ao Wi-Fi", "Redes, senha e segurança.", [
        ("explanation", "Entender", "O Wi-Fi conecta seus aparelhos à internet sem cabo. Redes com cadeado exigem senha; redes abertas são menos seguras."),
        ("example", "Ver um exemplo", "Nas configurações, escolha a rede de casa e digite a senha. O aparelho memoriza e reconecta sozinho depois."),
        ("practice", "Praticar", "Conecte o celular à rede de casa e depois desconecte. Observe a diferença entre o ícone de Wi-Fi e o de dados móveis."),
        ("check", "Verificar", "Evite acessar o banco em Wi-Fi aberto de lanchonete ou ônibus. Use os dados móveis nesses casos."),
        ("next", "Próximo passo", "Com internet estável, você aproveita melhor todos os serviços."),
    ]),
    ("info-bateria", "Cuidar da bateria", "Carregar e economizar energia.", [
        ("explanation", "Entender", "Baterias de lítio duram mais quando ficam entre 20% e 80%. Carregar a noite inteira todos os dias desgasta a capacidade com o tempo."),
        ("example", "Ver um exemplo", "Se o celular esquenta muito ao carregar, retire a capa. Calor é o maior inimigo da bateria."),
        ("practice", "Praticar", "Ative o modo de economia de energia e veja quais aplicativos consomem mais bateria no seu aparelho."),
        ("check", "Verificar", "Se a bateria acaba rápido mesmo carregada, veja a lista de consumo: um app em segundo plano pode ser o culpado."),
        ("next", "Próximo passo", "Bateria saudável significa menos recargas e mais durabilidade."),
    ]),
    ("info-acessibilidade", "Recursos de acessibilidade", "Zoom, leitor de tela e contraste.", [
        ("explanation", "Entender", "Os sistemas trazem recursos para quem precisa: aumentar o texto, leitor de tela que fala o que está escrito, alto contraste e legendas."),
        ("example", "Ver um exemplo", "Ativando o leitor de tela, o celular fala cada item que você toca. O zoom de tela aumenta a área visível com três toques."),
        ("practice", "Praticar", "Aumente o tamanho do texto do sistema e ative o modo de alto contraste. Depois volte ao tamanho normal."),
        ("check", "Verificar", "Se o leitor de tela ativou por engano, use o atalho de três toques para desligá-lo."),
        ("next", "Próximo passo", "Acessibilidade não é só para quem precisa: ajuda todo mundo."),
    ]),
    ("info-formatar", "Formatar um texto", "Negrito, itálico e alinhamento.", [
        ("explanation", "Entender", "Formatar é dar destaque e organização ao texto. Negrito destaca, itálico dá ênfase e o alinhamento define a posição na página."),
        ("example", "Ver um exemplo", "Selecione a palavra e use Ctrl+B para negrito, Ctrl+I para itálico e Ctrl+U para sublinhar. O botão de alinhamento centraliza o parágrafo."),
        ("practice", "Praticar", "Escreva um título e um parágrafo. Deixe o título em negrito e centralizado e o texto justificado."),
        ("check", "Verificar", "Não use negrito em parágrafos inteiros: perde o efeito. Destaque apenas as palavras-chave."),
        ("next", "Próximo passo", "Texto bem formatado é mais fácil de ler e de imprimir."),
    ]),
    ("info-pdf", "Trabalhar com PDF", "Abrir, preencher e assinar.", [
        ("explanation", "Entender", "PDF é um formato que mantém a aparência igual em qualquer aparelho. Serve para documentos finais, formulários e contratos."),
        ("example", "Ver um exemplo", "Para preencher, use a ferramenta de texto do leitor de PDF. Para assinar, use a assinatura digital do gov.br, que tem validade legal."),
        ("practice", "Praticar", "Abra um PDF de formulário, preencha os campos de texto e salve uma cópia."),
        ("check", "Verificar", "Depois de salvar, feche e abra de novo. Se os campos continuam preenchidos, o salvamento funcionou."),
        ("next", "Próximo passo", "PDF é o formato padrão para enviar documentos por e-mail."),
    ]),
    ("info-qrcode", "Ler um QR Code", "Abrir links e pagar.", [
        ("explanation", "Entender", "O QR Code é um quadrado com pontos que guarda um endereço ou um pagamento. A câmera do celular lê e abre o conteúdo."),
        ("example", "Ver um exemplo", "Abra a câmera, aponte para o código e toque no aviso que aparece. Em pagamentos, confira o valor e o nome antes de confirmar."),
        ("practice", "Praticar", "Leia um QR Code de um cardápio ou site conhecido e veja para onde ele leva antes de abrir."),
        ("check", "Verificar", "Nunca confirme um pagamento sem checar o nome do recebedor. Golpistas trocam QR Codes em locais públicos."),
        ("next", "Próximo passo", "QR Code é atalho para links, pagamentos e cardápios."),
    ]),
    ("info-backup", "Fazer backup", "Proteger seus arquivos.", [
        ("explanation", "Entender", "Backup é uma cópia de segurança dos seus arquivos. Se o aparelho quebrar ou for roubado, a cópia permite recuperar tudo."),
        ("example", "Ver um exemplo", "Manter as fotos na nuvem e uma cópia dos documentos no pendrive é backup em dois lugares, o ideal."),
        ("practice", "Praticar", "Escolha uma pasta importante, copie para a nuvem e confirme que os arquivos abrem de outro aparelho."),
        ("check", "Verificar", "Backup que nunca foi testado não é backup. Abra um arquivo da cópia e confirme que está íntegro."),
        ("next", "Próximo passo", "Com backup feito, você pode atualizar o aparelho sem medo."),
    ]),
    ("info-senhas-gestor", "Gerenciar várias senhas", "Organizar sem anotar no papel.", [
        ("explanation", "Entender", "Um gerenciador de senhas guarda todas as suas senhas com segurança e preenche automaticamente. Você só precisa lembrar de uma senha mestra."),
        ("example", "Ver um exemplo", "O navegador e o celular já têm gerenciadores integrados. Eles sugerem senhas fortes e as guardam vinculadas ao site."),
        ("practice", "Praticar", "Ative o gerenciador do seu navegador e salve duas senhas. Depois faça login em um site e veja o preenchimento automático."),
        ("check", "Verificar", "A senha mestra precisa ser forte e única. Se ela vazar, todas as outras ficam expostas."),
        ("next", "Próximo passo", "Com senhas organizadas, você deixa de repetir a mesma em tudo."),
    ]),
    ("info-ia", "Usar assistentes de IA", "Pedir ajuda e revisar respostas.", [
        ("explanation", "Entender", "Assistentes de IA respondem perguntas e ajudam a escrever, resumir e explicar. Eles podem errar, então a resposta precisa ser conferida."),
        ("example", "Ver um exemplo", "Pedir 'explique a conta de luz como se eu tivesse 10 anos' costuma dar uma resposta mais simples e clara."),
        ("practice", "Praticar", "Peça a um assistente para explicar um tema que você já conhece. Verifique se ele acertou."),
        ("check", "Verificar", "Nunca envie dados pessoais, senhas ou documentos com CPF para assistentes de IA."),
        ("next", "Próximo passo", "Usar IA com senso crítico acelera muito o aprendizado."),
    ]),
    ("info-codigo", "Primeiros passos em programação", "O que é um algoritmo.", [
        ("explanation", "Entender", "Algoritmo é uma sequência de passos para resolver um problema. Programar é escrever esses passos numa linguagem que o computador entende."),
        ("example", "Ver um exemplo", "Uma receita de bolo é um algoritmo: bater os ovos, acrescentar a farinha, assar. A ordem importa."),
        ("practice", "Praticar", "Escreva, em cinco passos, como você faz um café. Depois leia em voz alta e veja se faltou algum passo."),
        ("check", "Verificar", "Se outra pessoa conseguir seguir seus passos sem perguntar nada, o algoritmo está completo."),
        ("next", "Próximo passo", "Com a lógica pronta, você pode criar com blocos visuais."),
    ]),
    ("info-scratch", "Criar com blocos", "Lógica visual passo a passo.", [
        ("explanation", "Entender", "Programação em blocos monta instruções encaixando peças coloridas. Não precisa escrever código: a lógica é a mesma."),
        ("example", "Ver um exemplo", "Encaixe 'quando bandeira clicada', 'mova 10 passos' e 'repita 10 vezes'. O personagem anda pela tela."),
        ("practice", "Praticar", "Crie um projeto em que o personagem ande e diga 'Olá'. Teste clicando na bandeira verde."),
        ("check", "Verificar", "Se o personagem não se move, confira se os blocos estão encaixados na ordem certa, de cima para baixo."),
        ("next", "Próximo passo", "Depois dos blocos, você pode experimentar HTML."),
    ]),
    ("info-html", "Uma página web simples", "Título, texto e imagem.", [
        ("explanation", "Entender", "HTML é a linguagem que estrutura páginas da web. As tags dizem o que cada parte é: título, parágrafo, imagem ou link."),
        ("example", "Ver um exemplo", "<h1>Meu site</h1> cria o título, <p>Olá!</p> cria um parágrafo e <img src='foto.jpg'> mostra uma imagem."),
        ("practice", "Praticar", "Abra o Bloco de Notas, escreva um título e um parágrafo com tags e salve como pagina.html. Abra no navegador."),
        ("check", "Verificar", "Se aparecerem as tags em vez do texto, o arquivo foi salvo como .txt. Renomeie para .html e abra de novo."),
        ("next", "Próximo passo", "HTML organiza o conteúdo; CSS cuida da aparência."),
    ]),
    ("info-dados", "Entender dados e gráficos", "Transformar números em decisões.", [
        ("explanation", "Entender", "Dados são informações organizadas. Transformados em gráficos e tabelas, mostram padrões que os números soltos escondem."),
        ("example", "Ver um exemplo", "Anotar os gastos do mês e ver um gráfico revela que a maior despesa é transporte — e onde dá para economizar."),
        ("practice", "Praticar", "Anote seus gastos de uma semana em uma tabela e faça um gráfico de barras por categoria."),
        ("check", "Verificar", "A categoria com a barra mais alta é a que mais pesa. Isso confere com o que você sentiu no bolso?"),
        ("next", "Próximo passo", "Entender dados é o que sustenta boas decisões."),
    ]),
    ("info-privacidade", "Proteger sua privacidade", "O que compartilhar e o que não.", [
        ("explanation", "Entender", "Privacidade é decidir quem vê o quê. Dados como CPF, endereço, localização e fotos de documentos não devem circular livremente."),
        ("example", "Ver um exemplo", "Postar foto de documento ou dizer que está viajando informa a estranhos que sua casa está vazia."),
        ("practice", "Praticar", "Revise as permissões dos seus aplicativos: quais acessam localização, câmera e microfone? Desligue o que não faz sentido."),
        ("check", "Verificar", "Um app de lanterna precisa da sua localização? Se não precisa, negue a permissão."),
        ("next", "Próximo passo", "Privacidade protegida reduz golpes e riscos."),
    ]),
    ("info-etiqueta", "Boa convivência online", "Respeito e comunicação clara.", [
        ("explanation", "Entender", "Online vale a mesma educação do presencial: escrever com clareza, não gritar em maiúsculas e respeitar opiniões diferentes."),
        ("example", "Ver um exemplo", "Escrever tudo em maiúsculas é lido como grito. Áudios longos sem aviso incomodam: pergunte antes se a pessoa pode ouvir."),
        ("practice", "Praticar", "Antes de enviar uma mensagem, releia: está claro, educado e no canal certo? Ajuste se precisar."),
        ("check", "Verificar", "Se a resposta da outra pessoa parecer confusa ou ofendida, pergunte em vez de supor má intenção."),
        ("next", "Próximo passo", "Boa convivência melhora trabalho, família e amizades."),
    ]),
    ("info-acessivel", "Criar conteúdo acessível", "Texto alternativo e contraste.", [
        ("explanation", "Entender", "Conteúdo acessível pode ser usado por todos, inclusive por quem usa leitor de tela. Texto alternativo descreve imagens e bom contraste facilita a leitura."),
        ("example", "Ver um exemplo", "Na imagem de um gráfico, escreva 'gráfico de barras mostrando vendas por mês' em vez de 'imagem1.png'."),
        ("practice", "Praticar", "Escolha uma imagem, escreva um texto alternativo claro e verifique se o contraste do texto sobre o fundo é suficiente."),
        ("check", "Verificar", "Texto cinza claro sobre fundo branco cansa a vista. Escureça o texto ou o fundo."),
        ("next", "Próximo passo", "Criar para todos amplia o alcance do seu trabalho."),
    ]),
]
