"""Conteúdo pedagógico real — trilha Idiomas (32 módulos)."""

IDIOMAS = [
    ("idio-cumprimentos-en", "Cumprimentos em inglês", "Hello, good morning.", [
        ("explanation", "Entender", "Os cumprimentos mudam conforme a hora do dia. Good morning até o meio-dia, good afternoon à tarde e good evening à noite."),
        ("example", "Ver um exemplo", "Hello! Good morning, Ana. How are you? — I'm fine, thank you. E para se despedir: Goodbye! See you tomorrow!"),
        ("practice", "Praticar", "Diga em voz alta para três momentos do dia: de manhã, à tarde e à noite. Depois responda 'I'm fine, thank you' em voz alta."),
        ("check", "Verificar", "Você usou good morning de manhã e good evening à noite? O erro comum é trocar afternoon por evening."),
        ("next", "Próximo passo", "Com os cumprimentos prontos, você já pode se apresentar."),
    ]),
    ("idio-apresentar-en", "Me apresentar em inglês", "My name is... I am from Brazil.", [
        ("explanation", "Entender", "Para se apresentar, use My name is + nome. Para dizer de onde vem, I am from + lugar. Para a idade, I am + número + years old."),
        ("example", "Ver um exemplo", "My name is Pedro. I am from Brazil. I am thirty years old. I live in Barcelona. Nice to meet you!"),
        ("practice", "Praticar", "Escreva e fale sua apresentação em cinco frases: nome, origem, idade, cidade e uma despedida."),
        ("check", "Verificar", "Use 'I am', não 'I have', para idade. Em inglês se diz 'tenho 30 anos' como 'I am 30 years old'."),
        ("next", "Próximo passo", "Apresentado, o próximo passo são os números."),
    ]),
    ("idio-numeros-en", "Números em inglês", "One to twenty.", [
        ("explanation", "Entender", "De 1 a 12 os números têm nomes próprios. A partir do 13, formam-se com o final -teen; as dezenas terminam em -ty."),
        ("example", "Ver um exemplo", "One, two, three... ten. Depois: eleven, twelve, thirteen, fourteen, fifteen... E as dezenas: twenty, thirty, forty, fifty."),
        ("practice", "Praticar", "Conte de 1 a 20 em voz alta. Depois diga de 10 em 10 até 100: ten, twenty, thirty, forty..."),
        ("check", "Verificar", "Cuidado com a confusão entre thirteen (13) e thirty (30). A terminação -teen é a sílaba tônica no final."),
        ("next", "Próximo passo", "Números servem para preços, horas e telefones."),
    ]),
    ("idio-comida-en", "Comida em inglês", "Rice, beans, water, coffee.", [
        ("explanation", "Entender", "Os alimentos básicos têm nomes curtos e muito usados: rice (arroz), beans (feijão), bread (pão), water (água) e coffee (café)."),
        ("example", "Ver um exemplo", "I eat rice and beans every day. I drink coffee in the morning. I would like a glass of water, please."),
        ("practice", "Praticar", "Escreva a lista da sua comida de hoje em inglês. Depois diga em voz alta o que você come no café da manhã."),
        ("check", "Verificar", "Para pedir, use 'I would like...', que é mais educado que 'I want...'. Praticou assim?"),
        ("next", "Próximo passo", "Com comida, você já entende um cardápio simples."),
    ]),
    ("idio-cores-en", "Cores em inglês", "Red, blue, green.", [
        ("explanation", "Entender", "As cores básicas são red, blue, green, yellow, black e white. A cor vem antes do objeto: 'a red car', não 'a car red'."),
        ("example", "Ver um exemplo", "The sky is blue. The grass is green. I have a black bag and a white shirt."),
        ("practice", "Praticar", "Olhe ao redor e diga em inglês a cor de cinco objetos. Depois escreva: 'a red pen', 'a blue cup'."),
        ("check", "Verificar", "A ordem é cor + objeto. Se escreveu 'car red', inverta para 'red car'."),
        ("next", "Próximo passo", "Cores ajudam a descrever roupas e objetos no dia a dia."),
    ]),
    ("idio-dias-en", "Dias e meses em inglês", "Monday, January.", [
        ("explanation", "Entender", "Os dias da semana e os meses escrevem-se com letra maiúscula em inglês. A semana começa em Sunday ou Monday, conforme o calendário."),
        ("example", "Ver um exemplo", "Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday. Meses: January, February, March, April... December."),
        ("practice", "Praticar", "Diga em voz alta os dias da semana na ordem. Depois diga em que mês você nasceu e que dia é hoje."),
        ("check", "Verificar", "Cuidado com a pronúncia de Wednesday: lê-se 'uênz-dei', com o 'd' quase mudo."),
        ("next", "Próximo passo", "Datas e dias aparecem em consultas e compromissos."),
    ]),
    ("idio-familia-en", "Família em inglês", "Mother, father, sister.", [
        ("explanation", "Entender", "Os parentes próximos têm nomes próprios: mother (mãe), father (pai), sister (irmã), brother (irmão), son (filho) e daughter (filha)."),
        ("example", "Ver um exemplo", "This is my mother. She is a teacher. I have one sister and two brothers. My father is from Brazil."),
        ("practice", "Praticar", "Descreva sua família em quatro frases: quem são, o que fazem e onde vivem."),
        ("check", "Verificar", "Para dizer 'meu irmão', use my brother. Não use 'the my brother', que está errado em inglês."),
        ("next", "Próximo passo", "Família e cores permitem descrever pessoas e fotos."),
    ]),
    ("idio-mercado-en", "No mercado em inglês", "How much is this?", [
        ("explanation", "Entender", "Para perguntar preço, use How much is this? Para vários itens, How much are these? Para pedir, I would like..."),
        ("example", "Ver um exemplo", "How much is this bread? — It is two dollars. I would like three apples, please. Here is the money."),
        ("practice", "Praticar", "Simule uma compra: pergunte o preço de dois produtos, peça um item e agradeça."),
        ("check", "Verificar", "Use 'is' para um item e 'are' para vários. Confira se você escolheu o certo em cada pergunta."),
        ("next", "Próximo passo", "Comprar em inglês abre caminho para pedir informações na rua."),
    ]),
    ("idio-onibus-en", "Transporte em inglês", "Where is the bus stop?", [
        ("explanation", "Entender", "Para pedir informação, use Where is...? Os meios de transporte são bus, train, subway e taxi. O ponto de ônibus é bus stop."),
        ("example", "Ver um exemplo", "Excuse me, where is the bus stop? — It is over there, next to the bank. How much is the ticket?"),
        ("practice", "Praticar", "Pratique três perguntas: onde fica o ponto, quanto custa a passagem e a que horas passa o próximo ônibus."),
        ("check", "Verificar", "Comece sempre com 'Excuse me' para ser educado. Isso muda o tom da resposta."),
        ("next", "Próximo passo", "Transporte e direções resolvem boa parte de uma viagem."),
    ]),
    ("idio-medico-en", "No médico em inglês", "I have a headache.", [
        ("explanation", "Entender", "Para dizer o que sente, use I have a + sintoma: headache (dor de cabeça), fever (febre), stomachache (dor de barriga)."),
        ("example", "Ver um exemplo", "I have a headache and a fever. I need a doctor, please. Can you help me? I am allergic to penicillin."),
        ("practice", "Praticar", "Diga em voz alta três sintomas e peça ajuda: 'I need a doctor'. Depois diga se é alérgico a algum remédio."),
        ("check", "Verificar", "Sempre leve uma lista escrita de alergias e remédios de uso contínuo. Na urgência, não dá para improvisar."),
        ("next", "Próximo passo", "Saber pedir ajuda médica é o inglês mais importante em viagem."),
    ]),
    ("idio-trabalho-en", "No trabalho em inglês", "Can you help me?", [
        ("explanation", "Entender", "No trabalho, pedidos educados usam Can you...? ou Could you...? Para entender algo, peça: Can you repeat, please?"),
        ("example", "Ver um exemplo", "Can you help me with this report? Could you send me the file? Sorry, can you repeat, please?"),
        ("practice", "Praticar", "Escreva três pedidos de trabalho em inglês usando Can you e Could you. Diga em voz alta."),
        ("check", "Verificar", "'Could you' é mais formal que 'Can you'. Escolha conforme a pessoa for chefe, colega ou cliente."),
        ("next", "Próximo passo", "Esse vocabulário serve para reuniões e e-mails profissionais."),
    ]),
    ("idio-viagem-en", "Em viagem em inglês", "Where is the hotel?", [
        ("explanation", "Entender", "Em viagem, as perguntas essenciais são sobre lugar, preço e horário: Where is the hotel? How much is it? What time is check-in?"),
        ("example", "Ver um exemplo", "Where is the hotel? — Go straight and turn left. I have a reservation. My name is Pedro Belentani."),
        ("practice", "Praticar", "Simule um check-in: diga que tem reserva, confirme o número de noites e pergunte o horário do café da manhã."),
        ("check", "Verificar", "Tenha o nome da reserva escrito. Soletrar o sobrenome em inglês evita confusão na recepção."),
        ("next", "Próximo passo", "Com o básico de viagem, você resolve aeroporto, hotel e transporte."),
    ]),
    ("idio-cumprimentos-es", "Cumprimentos em espanhol", "Hola, buenos días.", [
        ("explanation", "Entender", "Em espanhol, buenos días é usado até o meio-dia, buenas tardes à tarde e buenas noches à noite, tanto para chegar quanto para se despedir."),
        ("example", "Ver um exemplo", "¡Hola! Buenos días, ¿cómo estás? — Muy bien, gracias. ¿Y tú? Adiós, hasta luego."),
        ("practice", "Praticar", "Diga os três cumprimentos em voz alta e responda 'muy bien, gracias'. Pratique com três pessoas diferentes."),
        ("check", "Verificar", "Note que buenos días é plural, com 's'. É o erro mais comum de quem fala português."),
        ("next", "Próximo passo", "Com os cumprimentos, você já pode se apresentar em espanhol."),
    ]),
    ("idio-apresentar-es", "Me apresentar em espanhol", "Me llamo... Soy de Brasil.", [
        ("explanation", "Entender", "Para se apresentar, use Me llamo + nome. Para origem, Soy de + lugar. Para idade, Tengo + número + años."),
        ("example", "Ver um exemplo", "Me llamo Pedro. Soy de Brasil. Tengo treinta años. Vivo en Barcelona. Mucho gusto."),
        ("practice", "Praticar", "Escreva e fale sua apresentação em cinco frases: nome, origem, idade, cidade e despedida."),
        ("check", "Verificar", "Em espanhol, idade usa 'tengo' (tenho), e não 'soy'. Isso é diferente do inglês — atenção para não misturar."),
        ("next", "Próximo passo", "Apresentado, o próximo passo são os números."),
    ]),
    ("idio-numeros-es", "Números em espanhol", "Uno al veinte.", [
        ("explanation", "Entender", "De 1 a 15 os números têm nomes próprios; do 16 ao 19 formam-se por composição. As dezenas terminam em -enta."),
        ("example", "Ver um exemplo", "Uno, dos, tres... diez. Depois once, doce, trece, catorce, quince. Dezenas: veinte, treinta, cuarenta, cincuenta."),
        ("practice", "Praticar", "Conte de 1 a 20 em voz alta. Depois conte de 10 em 10 até 100."),
        ("check", "Verificar", "Cuidado com 'catorce' (14) e 'cuarenta' (40), que soam parecidos. A tônica muda: ca-TOR-ce e cua-REN-ta."),
        ("next", "Próximo passo", "Com os números você lê preços, horários e endereços sem travar."),
    ]),
    ("idio-comida-es", "Comida em espanhol", "Arroz, frijoles, agua.", [
        ("explanation", "Entender", "Alimentos básicos em espanhol: arroz (arroz), frijoles (feijão), pan (pão), agua (água) e café (café)."),
        ("example", "Ver um exemplo", "Como arroz y frijoles todos los días. Bebo café por la mañana. Quisiera un vaso de agua, por favor."),
        ("practice", "Praticar", "Liste sua comida de hoje em espanhol e diga em voz alta o que come no café da manhã."),
        ("check", "Verificar", "Para pedir, 'quisiera' é mais educado que 'quiero'. Usou assim?"),
        ("next", "Próximo passo", "Com comida, você lê um cardápio simples."),
    ]),
    ("idio-falsos-amigos", "Falsos amigos PT-ES", "Exquisito, largo, oficina.", [
        ("explanation", "Entender", "Falsos amigos são palavras parecidas que significam coisas diferentes. Confundir é normal, mas muda completamente o sentido da frase."),
        ("example", "Ver um exemplo", "Exquisito em espanhol é 'delicioso', não 'esquisito'. Largo significa 'comprido', não 'largo'. Oficina é 'escritório', não 'oficina mecânica'."),
        ("practice", "Praticar", "Anote cinco falsos amigos e escreva uma frase com cada um, no sentido correto do espanhol."),
        ("check", "Verificar", "Ao ouvir uma palavra parecida, desconfie antes de traduzir direto. O contexto resolve."),
        ("next", "Próximo passo", "Evitar falsos amigos evita mal-entendidos embaraçosos."),
    ]),
    ("idio-mercado-es", "No mercado em espanhol", "¿Cuánto cuesta?", [
        ("explanation", "Entender", "Para perguntar o preço, use ¿Cuánto cuesta? no singular e ¿Cuánto cuestan? no plural. Para pedir, Quisiera..."),
        ("example", "Ver um exemplo", "¿Cuánto cuesta este pan? — Cuesta dos euros. Quisiera tres manzanas, por favor. Aquí tiene el dinero."),
        ("practice", "Praticar", "Simule uma compra: pergunte o preço de dois produtos, peça um item e agradeça."),
        ("check", "Verificar", "Confira se usou cuesta para um item e cuestan para vários. É o mesmo erro de is/are em inglês."),
        ("next", "Próximo passo", "Comprar em espanhol serve para pedir informação na rua."),
    ]),
    ("idio-viagem-es", "Em viagem em espanhol", "¿Dónde está el hotel?", [
        ("explanation", "Entender", "As perguntas essenciais de viagem são ¿Dónde está...?, ¿Cuánto cuesta? e ¿A qué hora...? O hotel é el hotel e a reserva é la reserva."),
        ("example", "Ver um exemplo", "¿Dónde está el hotel? — Siga recto y gire a la izquierda. Tengo una reserva a nombre de Pedro Belentani."),
        ("practice", "Praticar", "Simule um check-in: diga que tem reserva, confirme as noites e pergunte o horário do café da manhã."),
        ("check", "Verificar", "Tenha o nome da reserva escrito. Soletrar o sobrenome evita confusão na recepção."),
        ("next", "Próximo passo", "Com o básico, você resolve aeroporto, hotel e transporte."),
    ]),
    ("idio-medico-es", "No médico em espanhol", "Me duele la cabeza.", [
        ("explanation", "Entender", "Para dizer o que dói, use Me duele + a parte do corpo: la cabeza (cabeça), el estómago (estômago), la garganta (garganta)."),
        ("example", "Ver um exemplo", "Me duele la cabeza y tengo fiebre. Necesito un médico, por favor. ¿Puede ayudarme?"),
        ("practice", "Praticar", "Diga em voz alta três sintomas e peça ajuda: 'Necesito un médico'. Depois informe suas alergias."),
        ("check", "Verificar", "'Me duele' é para uma dor e 'me duelen' para várias. Confira se escolheu o certo."),
        ("next", "Próximo passo", "Pedir ajuda médica é o espanhol mais útil em viagem."),
    ]),
    ("idio-pt-estrangeiros", "Português para estrangeiros", "Bom dia! Como falar no Brasil.", [
        ("explanation", "Entender", "O português do Brasil é falado de forma mais aberta e com entonação cantada. As vogais finais são mais claras que em Portugal."),
        ("example", "Ver um exemplo", "Bom dia! Como você se chama? — Meu nome é Ana. Prazer em conhecer você. De onde você é?"),
        ("practice", "Praticar", "Pratique três apresentações: formal (senhor/senhora), informal (você) e muito informal (você, tudo bem?)."),
        ("check", "Verificar", "Use 'você' no Brasil em quase todas as situações. 'Tu' é regional e varia muito entre estados."),
        ("next", "Próximo passo", "Depois da apresentação, vêm as perguntas do dia a dia."),
    ]),
    ("idio-entrevista-pt", "Entrevista de trabalho", "Perguntas comuns e respostas.", [
        ("explanation", "Entender", "Entrevistas seguem um roteiro: fale sobre você, sua experiência, seus pontos fortes e por que quer a vaga. Respostas curtas e concretas funcionam melhor."),
        ("example", "Ver um exemplo", "Fale sobre você: 'Trabalho com tecnologia há dez anos, principalmente em automação.' Por que esta vaga? 'Porque quero aplicar isso em educação.'"),
        ("practice", "Praticar", "Grave-se respondendo em voz alta: 'Fale sobre você' e 'Qual é seu maior ponto forte?'. Ouça e ajuste."),
        ("check", "Verificar", "Nunca invente experiência nem formação. Mentira descoberta elimina a candidatura e mancha o currículo."),
        ("next", "Próximo passo", "Depois da entrevista, o e-mail profissional fecha o ciclo."),
    ]),
    ("idio-telefone-pt", "Falar ao telefone", "Atenção, quem fala?", [
        ("explanation", "Entender", "Ao telefone, a primeira frase é Alô! ou Atenção. Depois, quem fala identifica-se: 'Aqui é o Pedro'. Para pedir para repetir: 'Pode repetir, por favor?'"),
        ("example", "Ver um exemplo", "Alô, bom dia! Aqui é o Pedro Belentani. Gostaria de falar com a Ana, por favor. — Um momento, vou transferir."),
        ("practice", "Praticar", "Simule três ligações: pedir informação, marcar consulta e deixar recado. Fale em voz alta."),
        ("check", "Verificar", "Sem ver a pessoa, articule mais devagar e confirme dados: 'Então é 15 de março, correto?'"),
        ("next", "Próximo passo", "Telefone e e-mail profissional se completam."),
    ]),
    ("idio-email-pt", "Escrever e-mail profissional", "Assunto, saudação e despedida.", [
        ("explanation", "Entender", "Um e-mail profissional tem assunto claro, saudação, mensagem objetiva e despedida. Assunto vago faz a mensagem ser ignorada."),
        ("example", "Ver um exemplo", "Assunto: Solicitação de matrícula. Prezados, bom dia. Gostaria de informações sobre a matrícula. Atenciosamente, Pedro Belentani."),
        ("practice", "Praticar", "Escreva um e-mail pedindo informação sobre um curso. Use assunto, saudação, dois parágrafos e despedida."),
        ("check", "Verificar", "Releia antes de enviar: tem erro de digitação? O anexo foi anexado? O assunto resume o pedido?"),
        ("next", "Próximo passo", "E-mail bem escrito abre portas para reuniões e apresentações."),
    ]),
    ("idio-apresentacao-pt", "Fazer uma apresentação", "Estrutura e linguagem.", [
        ("explanation", "Entender", "Uma boa apresentação tem abertura, três pontos principais e conclusão. Diga o que vai falar, fale, e resuma o que falou."),
        ("example", "Ver um exemplo", "Abertura: 'Vou apresentar três resultados.' Meio: 'Primeiro... Segundo... Terceiro...' Fecho: 'Em resumo, crescemos 20%.'"),
        ("practice", "Praticar", "Prepare uma apresentação de dois minutos sobre um tema que você domina. Use a estrutura de três pontos."),
        ("check", "Verificar", "Cronometre. Se passou de dois minutos, corte o menos importante — o público perdoa o curto, não o longo."),
        ("next", "Próximo passo", "Apresentar bem ajuda em reuniões e entrevistas."),
    ]),
    ("idio-reuniao-pt", "Participar de uma reunião", "Concordar e discordar.", [
        ("explanation", "Entender", "Em reunião, é preciso pedir a palavra, concordar e discordar com respeito. Frases prontas ajudam: 'Posso complementar?'"),
        ("example", "Ver um exemplo", "Concordar: 'Concordo com a Ana.' Discordar: 'Entendo, mas vejo de outra forma.' Pedir tempo: 'Posso pensar e responder amanhã?'"),
        ("practice", "Praticar", "Simule uma reunião: faça uma pergunta, concorde com um ponto e discorde com educação de outro."),
        ("check", "Verificar", "Discorde da ideia, não da pessoa. Frases como 'vejo de outra forma' evitam conflito desnecessário."),
        ("next", "Próximo passo", "Reuniões pedem também clareza na escrita."),
    ]),
    ("idio-escrita-pt", "Escrever com clareza", "Frases curtas e diretas.", [
        ("explanation", "Entender", "Escrever claro é escrever para o outro entender rápido. Frases curtas, uma ideia por frase e voz ativa resolvem a maior parte."),
        ("example", "Ver um exemplo", "Em vez de 'Foi decidido pela equipe que o prazo seria prorrogado', escreva 'A equipe prorrogou o prazo.'"),
        ("practice", "Praticar", "Reescreva três frases longas em frases curtas e diretas. Leia em voz alta para testar."),
        ("check", "Verificar", "Se você precisa reler para entender, reescreva. Texto claro se entende na primeira leitura."),
        ("next", "Próximo passo", "Escrita clara melhora e-mail, currículo e relatórios."),
    ]),
    ("idio-leitura-en", "Ler um texto curto em inglês", "Ideia principal.", [
        ("explanation", "Entender", "Para ler em inglês, não traduza palavra por palavra. Procure a ideia principal: geralmente está na primeira frase de cada parágrafo."),
        ("example", "Ver um exemplo", "Em 'The bus leaves at eight. It stops downtown.', a ideia principal é o horário de saída: eight."),
        ("practice", "Praticar", "Leia uma notícia curta em inglês e escreva, em português, a ideia principal em uma frase."),
        ("check", "Verificar", "Se você resumiu em uma frase, entendeu o essencial. Se não conseguiu, leia só o primeiro parágrafo."),
        ("next", "Próximo passo", "Ler e ouvir se reforçam mutuamente — treine os dois todos os dias."),
    ]),
    ("idio-escuta-en", "Ouvir e entender inglês", "Palavras-chave.", [
        ("explanation", "Entender", "Ao ouvir inglês, não tente pegar tudo. Escute as palavras-chave: quem, o que, quando e onde. O resto se deduz pelo contexto."),
        ("example", "Ver um exemplo", "Em 'The train to London leaves at nine', as palavras-chave são train, London e nine."),
        ("practice", "Praticar", "Ouça um áudio curto em inglês e anote três palavras-chave. Depois tente dizer o que aconteceu."),
        ("check", "Verificar", "Repita o mesmo áudio três vezes. Na terceira, você entende bem mais — a audição melhora com repetição."),
        ("next", "Próximo passo", "Ouvir bem prepara para falar com mais confiança."),
    ]),
    ("idio-pronuncia-en", "Pronúncia em inglês", "Sons difíceis.", [
        ("explanation", "Entender", "O inglês tem sons que não existem em português, como o 'th' de think e o 'r' de red. A boca se move de forma diferente."),
        ("example", "Ver um exemplo", "Em think, a língua toca de leve os dentes de cima. Em thank, o mesmo som. Em red, a língua não toca o céu da boca."),
        ("practice", "Praticar", "Repita em voz alta cinco vezes: think, thank, three, red, right. Grave-se e compare com um áudio nativo."),
        ("check", "Verificar", "Se 'think' saiu como 'sink' ou 'tink', a língua não tocou os dentes. Ajuste e repita."),
        ("next", "Próximo passo", "Pronúncia se ganha com repetição diária curta."),
    ]),
    ("idio-pronuncia-es", "Pronúncia em espanhol", "Sons e ritmo.", [
        ("explanation", "Entender", "O espanhol é mais regular que o português: cada letra tem som fixo. O 'r' é mais suave e o 'j' soa como um sopro forte."),
        ("example", "Ver um exemplo", "Em espanhol, 'j' de jardín soa como um 'r' forte de português. O 'll' de llave soa como 'i' ou 'lh', dependendo do país."),
        ("practice", "Praticar", "Repita em voz alta: jardín, llave, perro, pero. Note a diferença entre perro (cachorro) e pero (mas)."),
        ("check", "Verificar", "Trocar perro por pero muda completamente o sentido. Pratique a diferença até ouvir a distinção."),
        ("next", "Próximo passo", "Com a pronúncia, você fala com mais confiança."),
    ]),
    ("idio-cultura-br", "Cultura brasileira", "Regiões, festas e costumes.", [
        ("explanation", "Entender", "O Brasil tem cinco regiões com sotaques, comidas e festas próprias. Conhecer isso ajuda a entender piadas, expressões e o jeito de conversar."),
        ("example", "Ver um exemplo", "O Nordeste tem o forró e o acarajé; o Sul, a festa da uva e o chimarrão; o Norte, o açaí e o Círio de Nazaré."),
        ("practice", "Praticar", "Escolha uma região, pesquise uma festa e uma comida típica e conte em três frases o que descobriu."),
        ("check", "Verificar", "Evite generalizar: 'todos os brasileiros...' quase nunca é verdade em um país tão grande."),
        ("next", "Próximo passo", "Cultura e idioma caminham juntos — você termina esta trilha falando com mais contexto."),
    ]),
]
