"""Conteúdo pedagógico real — trilha Matemática (40 módulos).

Cada item: (id, título, subtítulo, [(tipo, título, texto), ...])
Cinco etapas por módulo: explanation, example, practice, check, next.
"""

MATEMATICA = [
    ("mat-contar", "Contar até 100", "Contagem com objetos do dia a dia.", [
        ("explanation", "Entender", "Contar é associar um número a cada objeto, sem pular nem repetir. Os números crescem de um em um: 1, 2, 3... Depois do 9 vem o 10, e a contagem recomeça no 1 com uma dezena guardada."),
        ("example", "Ver um exemplo", "Conte os dedos das duas mãos: 1, 2, 3, 4, 5 na esquerda e 6, 7, 8, 9, 10 na direita. Dez dedos são exatamente uma dezena."),
        ("practice", "Praticar", "Conte de 1 a 20 tocando cada objeto da mesa. Depois conte de 10 em 10 até 100: 10, 20, 30... 100."),
        ("check", "Verificar", "Você chegou ao 100 sem pular número? Se travou em algum, conte de novo a partir do último que acertou."),
        ("next", "Próximo passo", "Contar de um em um já está firme. Agora você pode somar quantidades."),
    ]),
    ("mat-soma", "Somar com as mãos", "2 + 3 com dedos e desenhos.", [
        ("explanation", "Entender", "Somar é juntar duas quantidades em uma só. O sinal + significa 'mais'. Se você tem 2 e ganha 3, passa a ter 5."),
        ("example", "Ver um exemplo", "Levante 2 dedos de uma mão e 3 da outra. Junte todos: 1, 2, 3, 4, 5. Então 2 + 3 = 5."),
        ("practice", "Praticar", "Resolva usando os dedos: 4 + 1, 3 + 3, 5 + 2, 6 + 4. Diga o resultado em voz alta."),
        ("check", "Verificar", "Para conferir 6 + 4, comece do 6 e conte mais quatro: 7, 8, 9, 10. Deu o mesmo resultado?"),
        ("next", "Próximo passo", "Somar juntando já funciona. O caminho inverso é a subtração."),
    ]),
    ("mat-subtracao", "Subtrair na prática", "Tinha 5, tirei 2.", [
        ("explanation", "Entender", "Subtrair é tirar uma quantidade de outra. O sinal − significa 'menos'. Se você tinha 5 e tirou 2, sobram 3."),
        ("example", "Ver um exemplo", "Coloque 5 tampinhas na mesa e retire 2. Conte as que ficaram: 1, 2, 3. Então 5 − 2 = 3."),
        ("practice", "Praticar", "Resolva com objetos: 7 − 3, 9 − 4, 10 − 5, 6 − 1. Escreva cada resultado."),
        ("check", "Verificar", "Confira somando de volta: se 9 − 4 = 5, então 5 + 4 precisa dar 9. Deu?"),
        ("next", "Próximo passo", "Somar e subtrair são caminhos inversos. Você já domina os dois."),
    ]),
    ("mat-dinheiro", "Contar dinheiro", "Moedas e notas do real.", [
        ("explanation", "Entender", "O real (R$) usa moedas de 5, 10, 25 e 50 centavos e de 1 real, além de notas de 2, 5, 10, 20, 50 e 100 reais. Cem centavos formam 1 real."),
        ("example", "Ver um exemplo", "Quatro moedas de 25 centavos somam 100 centavos, ou seja, R$ 1,00. Duas notas de R$ 50 somam R$ 100,00."),
        ("practice", "Praticar", "Separe as moedas que você tiver por valor. Some primeiro as de 25, depois as de 10, as de 5 e as de 1. Qual é o total?"),
        ("check", "Verificar", "Reconte agrupando de dez em dez centavos. Se chegar ao mesmo total por dois caminhos, sua conta está certa."),
        ("next", "Próximo passo", "Saber contar dinheiro abre caminho para calcular o troco."),
    ]),
    ("mat-troco", "Calcular o troco", "Paguei R$10, quanto volta?", [
        ("explanation", "Entender", "Troco é o dinheiro que volta quando você paga mais do que o preço. Para achar o troco, subtraia o preço do valor pago."),
        ("example", "Ver um exemplo", "O pão custa R$ 6,00 e você paga com R$ 10,00. Troco = 10 − 6 = R$ 4,00."),
        ("practice", "Praticar", "Calcule: compra de R$ 7,50 paga com R$ 10,00. Compra de R$ 3,20 paga com R$ 5,00. Compra de R$ 12,00 paga com R$ 20,00."),
        ("check", "Verificar", "Confira somando o troco ao preço: troco + preço deve dar exatamente o valor pago."),
        ("next", "Próximo passo", "Com o troco dominado, o próximo passo é comparar preços."),
    ]),
    ("mat-multiplicar", "Multiplicar é repetir", "3 vezes 4 = 4+4+4.", [
        ("explanation", "Entender", "Multiplicar é somar a mesma quantidade várias vezes. O sinal × significa 'vezes'. Três vezes quatro é o mesmo que quatro, três vezes seguidas."),
        ("example", "Ver um exemplo", "3 × 4 = 4 + 4 + 4 = 12. Também vale na ordem inversa: 4 × 3 = 3 + 3 + 3 + 3 = 12."),
        ("practice", "Praticar", "Resolva somando: 2 × 5, 3 × 3, 4 × 2, 5 × 3. Depois escreva cada um como soma repetida."),
        ("check", "Verificar", "Confira trocando a ordem: 3 × 4 e 4 × 3 devem dar o mesmo resultado. Deram?"),
        ("next", "Próximo passo", "Multiplicar é somar em atalho. Dividir é o caminho de volta."),
    ]),
    ("mat-dividir", "Dividir para repartir", "12 balas para 3 pessoas.", [
        ("explanation", "Entender", "Dividir é repartir uma quantidade em partes iguais. O sinal ÷ significa 'dividido por'. Doze balas para três pessoas dão quatro para cada uma."),
        ("example", "Ver um exemplo", "12 ÷ 3 = 4, porque 3 × 4 = 12. Quando sobra algo que não dá para repartir igualmente, chamamos de resto."),
        ("practice", "Praticar", "Resolva: 8 ÷ 2, 15 ÷ 3, 20 ÷ 4, 14 ÷ 2. Use objetos para conferir."),
        ("check", "Verificar", "Multiplique o resultado pelo divisor: 4 × 3 = 12. Se voltar ao número inicial, a divisão está certa."),
        ("next", "Próximo passo", "Repartir igualmente é a base para frações e porcentagens."),
    ]),
    ("mat-medidas", "Medir comprimento", "Metro e centímetro.", [
        ("explanation", "Entender", "Comprimento se mede em metros (m) e centímetros (cm). Um metro tem exatamente cem centímetros. A fita métrica mostra as duas escalas."),
        ("example", "Ver um exemplo", "Uma porta tem cerca de 2 metros, ou 200 centímetros. A mão aberta de um adulto mede perto de 20 centímetros."),
        ("practice", "Praticar", "Com uma fita métrica, meça a largura da mesa, a altura da porta e o comprimento do sofá. Anote em centímetros."),
        ("check", "Verificar", "Converta o que mediu para metros dividindo por 100. Se a mesa tem 120 cm, isso é 1,20 m."),
        ("next", "Próximo passo", "Medir comprimento ajuda a calcular área mais adiante."),
    ]),
    ("mat-peso", "Medir peso", "Quilos e gramas.", [
        ("explanation", "Entender", "Peso se mede em quilogramas (kg) e gramas (g). Um quilograma tem mil gramas. O quilo é a unidade do mercado; a grama, das porções pequenas."),
        ("example", "Ver um exemplo", "Um pacote de arroz de 1 kg tem 1000 g. Uma barra de chocolate de 100 g é 0,1 kg, ou seja, um décimo do quilo."),
        ("practice", "Praticar", "Leia os pesos de cinco produtos na despensa. Anote quantos gramas cada um tem."),
        ("check", "Verificar", "Some dois produtos: 500 g + 500 g = 1000 g = 1 kg. A conversão fez sentido?"),
        ("next", "Próximo passo", "Peso e capacidade seguem a mesma lógica de conversão."),
    ]),
    ("mat-horas", "Ler as horas", "Relógio analógico e digital.", [
        ("explanation", "Entender", "O dia tem 24 horas e cada hora tem 60 minutos. No relógio de ponteiros, o curto marca a hora e o longo marca os minutos."),
        ("example", "Ver um exemplo", "Quando o ponteiro longo está no 12 e o curto no 3, são 3 horas. Com o longo no 6, são 3 e meia, ou 3:30."),
        ("practice", "Praticar", "Olhe para um relógio agora e escreva a hora. Depois diga que horas serão daqui a duas horas e daqui a meia hora."),
        ("check", "Verificar", "Some os minutos: se são 14:40, faltam 20 minutos para as 15:00. Você chegou ao mesmo resultado?"),
        ("next", "Próximo passo", "Ler horas permite calcular duração e organizar o dia."),
    ]),
    ("mat-calendario", "Usar o calendário", "Dias, semanas e meses.", [
        ("explanation", "Entender", "Uma semana tem 7 dias, um mês tem cerca de 30 dias e um ano tem 12 meses, ou 365 dias."),
        ("example", "Ver um exemplo", "Janeiro tem 31 dias, fevereiro tem 28 (ou 29 em ano bissexto), março tem 31. Somando os doze meses chega-se a 365."),
        ("practice", "Praticar", "Veja o calendário do mês: que dia é hoje, que dia da semana, e quantos dias faltam para o fim do mês?"),
        ("check", "Verificar", "Escolha uma data daqui a três semanas e conte os dias. Confira se o dia da semana bate."),
        ("next", "Próximo passo", "Com o calendário dominado, você pode planejar prazos e compromissos."),
    ]),
    ("mat-receita", "Matemática na receita", "Dobrar e reduzir à metade.", [
        ("explanation", "Entender", "Receitas usam proporção: se você dobra a quantidade de pessoas, dobra cada ingrediente. Se reduz à metade, divide tudo por dois."),
        ("example", "Ver um exemplo", "Uma receita para 2 pessoas usa 2 xícaras de farinha. Para 4 pessoas, use 4 xícaras. Para 1 pessoa, use 1 xícara."),
        ("practice", "Praticar", "Pegue uma receita de bolo para 4 pessoas e escreva as quantidades para 8 pessoas e depois para 2 pessoas."),
        ("check", "Verificar", "Confira se a proporção se manteve: todas as quantidades dobraram, e não apenas algumas?"),
        ("next", "Próximo passo", "Proporções aparecem também em descontos e regra de três."),
    ]),
    ("mat-grafico", "Ler um gráfico", "Barras e linhas.", [
        ("explanation", "Entender", "Um gráfico de barras compara quantidades: quanto mais alta a barra, maior o valor. O gráfico de linhas mostra como algo muda ao longo do tempo."),
        ("example", "Ver um exemplo", "Numa pesquisa, banana teve 50 votos, maçã 30 e laranja 20. No gráfico de barras, a barra da banana é a mais alta."),
        ("practice", "Praticar", "Anote quantas horas você dormiu em cada dia desta semana e desenhe um gráfico de barras."),
        ("check", "Verificar", "Qual barra ficou mais alta? Isso corresponde ao dia em que você dormiu mais? O gráfico conta a mesma história dos números?"),
        ("next", "Próximo passo", "Gráficos resumem dados. Tabelas fazem o mesmo, com mais precisão."),
    ]),
    ("mat-porcentagem", "Porcentagem no dia a dia", "Desconto de 20%.", [
        ("explanation", "Entender", "Porcentagem é uma parte de cada cem. Vinte por cento (20%) significa 20 de cada 100. Para calcular, multiplique o valor pela porcentagem e divida por 100."),
        ("example", "Ver um exemplo", "Uma blusa de R$ 80 com 20% de desconto: 80 × 20 ÷ 100 = 16. O desconto é R$ 16, então você paga R$ 64."),
        ("practice", "Praticar", "Calcule: 10% de R$ 80, 25% de R$ 200 e 50% de R$ 120. Diga quanto sobra em cada caso."),
        ("check", "Verificar", "Lembre dos atalhos: 10% é dividir por 10, 50% é a metade e 25% é a metade da metade. Os resultados batem?"),
        ("next", "Próximo passo", "Porcentagem é a base dos juros e dos descontos do comércio."),
    ]),
    ("mat-fracoes", "Frações na pizza", "Metade, terço e quarto.", [
        ("explanation", "Entender", "Uma fração mostra partes de um todo dividido em partes iguais. Em 1/2, o número de baixo diz em quantas partes se dividiu e o de cima, quantas se tomaram."),
        ("example", "Ver um exemplo", "Uma pizza cortada em 4 fatias iguais: cada fatia é 1/4. Duas fatias são 2/4, que é o mesmo que 1/2 da pizza."),
        ("practice", "Praticar", "Divida um papel em quatro partes iguais e pinte 1/4, 2/4 e 3/4. Depois escreva qual delas é a metade."),
        ("check", "Verificar", "Some as partes: 1/4 + 1/4 + 1/4 + 1/4 precisa dar o papel inteiro, ou seja, 4/4 = 1."),
        ("next", "Próximo passo", "Frações e porcentagens são duas formas de falar da mesma ideia."),
    ]),
    ("mat-formas", "Formas geométricas", "Círculo, quadrado e triângulo.", [
        ("explanation", "Entender", "Formas planas têm lados e cantos. O quadrado tem 4 lados iguais, o retângulo tem 4 lados com dois pares iguais, o triângulo tem 3 lados e o círculo não tem lados."),
        ("example", "Ver um exemplo", "Uma janela é um retângulo, um azulejo é um quadrado, uma placa de trânsito pode ser um triângulo e um prato é um círculo."),
        ("practice", "Praticar", "Procure em casa três objetos para cada forma: quadrado, retângulo, triângulo e círculo."),
        ("check", "Verificar", "Para cada objeto, conte os lados. O quadrado e o retângulo têm 4; o triângulo, 3; o círculo, nenhum."),
        ("next", "Próximo passo", "Conhecer as formas é o primeiro passo para calcular área."),
    ]),
    ("mat-area", "Área e perímetro", "Medir um terreno.", [
        ("explanation", "Entender", "Perímetro é a soma de todos os lados, o contorno da figura. Área é o espaço de dentro, medida em metros quadrados (m²)."),
        ("example", "Ver um exemplo", "Um quarto de 3 m por 4 m tem perímetro 3 + 4 + 3 + 4 = 14 m e área 3 × 4 = 12 m²."),
        ("practice", "Praticar", "Meça a largura e o comprimento do seu quarto. Calcule o perímetro e a área."),
        ("check", "Verificar", "A área usa multiplicação e o perímetro usa soma. Você usou a operação certa em cada um?"),
        ("next", "Próximo passo", "Com área você calcula quanto piso ou tinta precisa comprar."),
    ]),
    ("mat-angulos", "Ângulos", "Reto, agudo e obtuso.", [
        ("explanation", "Entender", "Ângulo é a abertura entre duas linhas que se encontram. O ângulo reto tem 90 graus, como o canto de um livro. Menor que isso é agudo; maior, obtuso."),
        ("example", "Ver um exemplo", "O canto de uma porta aberta a 90 graus é um ângulo reto. Uma escada encostada na parede forma um ângulo agudo com o chão."),
        ("practice", "Praticar", "Olhe para os ponteiros de um relógio às 3 horas, às 6 horas e à 1 hora. Classifique cada ângulo como reto, agudo ou obtuso."),
        ("check", "Verificar", "Compare cada ângulo com o canto de um livro. Se for igual, é reto; se for menor, agudo; se for maior, obtuso."),
        ("next", "Próximo passo", "Ângulos aparecem em construção, mapas e direções."),
    ]),
    ("mat-regra3", "Regra de três simples", "Proporções do cotidiano.", [
        ("explanation", "Entender", "Regra de três serve para descobrir um valor quando dois outros são proporcionais. Multiplica-se em cruz e divide-se pelo número que sobra."),
        ("example", "Ver um exemplo", "Se 2 cadernos custam R$ 10, quanto custam 5? Monte 2/10 = 5/x. Multiplique 5 × 10 = 50 e divida por 2: R$ 25."),
        ("practice", "Praticar", "Se 3 pães custam R$ 9, quanto custam 7? Monte a proporção e resolva."),
        ("check", "Verificar", "Confira se o resultado faz sentido: 7 pães devem custar mais que 3 pães, e menos que o dobro de 9."),
        ("next", "Próximo passo", "Regra de três resolve receitas, receitas de obra e comparações de preço."),
    ]),
    ("mat-sequencias", "Sequências e padrões", "Descobrir o próximo número.", [
        ("explanation", "Entender", "Uma sequência segue uma regra. Descobrir o padrão é achar o que se repete ou quanto se soma a cada passo."),
        ("example", "Ver um exemplo", "Na sequência 2, 4, 6, 8, cada número aumenta de 2. O próximo é 10. Em 1, 3, 9, 27, cada um é o triplo do anterior."),
        ("practice", "Praticar", "Descubra o próximo número: 5, 10, 15, 20... e 100, 90, 80, 70... e 1, 2, 4, 8..."),
        ("check", "Verificar", "Diga a regra em voz alta: 'soma 5', 'subtrai 10', 'dobra'. Se a regra vale para todos os pares, está certa."),
        ("next", "Próximo passo", "Padrões são a porta de entrada para a álgebra."),
    ]),
    ("mat-equacao", "Equações simples", "Descobrir o valor de x.", [
        ("explanation", "Entender", "Uma equação diz que duas coisas são iguais. Resolver é descobrir o valor escondido, fazendo a operação inversa dos dois lados."),
        ("example", "Ver um exemplo", "Em x + 3 = 10, tire 3 dos dois lados: x = 10 − 3 = 7. Em 2x = 8, divida os dois lados por 2: x = 4."),
        ("practice", "Praticar", "Resolva: x + 5 = 12, x − 4 = 6, 3x = 15, x ÷ 2 = 5."),
        ("check", "Verificar", "Troque o x pelo valor encontrado e refaça a conta. Se os dois lados ficarem iguais, você acertou."),
        ("next", "Próximo passo", "Equações resolvem problemas de dinheiro, tempo e medidas."),
    ]),
    ("mat-negativos", "Números negativos", "Temperatura e dívidas.", [
        ("explanation", "Entender", "Números negativos ficam abaixo do zero e se escrevem com o sinal −. Servem para temperaturas frias, dívidas e saldos devedores."),
        ("example", "Ver um exemplo", "Se está 3 graus e a temperatura cai 5 graus, fica −2 graus. Se você deve R$ 50, seu saldo é −50."),
        ("practice", "Praticar", "Calcule: −3 + 5, 4 − 7, −2 − 3 e o saldo de quem tem R$ 20 e deve R$ 35."),
        ("check", "Verificar", "Use uma reta numérica desenhada no papel e caminhe para a direita ao somar e para a esquerda ao subtrair."),
        ("next", "Próximo passo", "Negativos completam a reta numérica e aparecem em gráficos."),
    ]),
    ("mat-estatistica", "Média e mediana", "Resumir um conjunto de dados.", [
        ("explanation", "Entender", "A média soma todos os valores e divide pela quantidade. A mediana é o valor do meio quando os dados estão em ordem."),
        ("example", "Ver um exemplo", "Notas 7, 8 e 9: a média é (7 + 8 + 9) ÷ 3 = 8. A mediana também é 8, o valor do meio."),
        ("practice", "Praticar", "Anote as idades das pessoas da sua casa, coloque em ordem e calcule a média e a mediana."),
        ("check", "Verificar", "Se um valor muito alto entrar na lista, a média sobe bastante e a mediana quase não muda. Isso aconteceu nos seus dados?"),
        ("next", "Próximo passo", "Média e mediana ajudam a interpretar pesquisas e salários."),
    ]),
    ("mat-probabilidade", "Probabilidade", "Chance de acontecer.", [
        ("explanation", "Entender", "Probabilidade mede a chance de um resultado acontecer. Vai de 0, impossível, até 1, certo. Calcula-se dividindo os casos favoráveis pelo total de casos."),
        ("example", "Ver um exemplo", "Ao jogar uma moeda, há 1 chance em 2 de dar cara, ou seja, 50%. Ao jogar um dado, a chance de sair 6 é 1 em 6."),
        ("practice", "Praticar", "Jogue uma moeda 20 vezes e anote quantas caras saíram. Depois divida pelo total e compare com 50%."),
        ("check", "Verificar", "Com poucas jogadas o resultado varia muito. Repita 100 vezes e veja se chega mais perto da metade."),
        ("next", "Próximo passo", "Probabilidade explica seguros, jogos e previsões do tempo."),
    ]),
    ("mat-juros", "Juros simples", "Entender um empréstimo.", [
        ("explanation", "Entender", "Juros são o valor pago pelo uso do dinheiro emprestado. Nos juros simples, calcula-se sempre sobre o valor inicial: valor × taxa × tempo."),
        ("example", "Ver um exemplo", "R$ 1.000 a 2% ao mês por 3 meses: juros = 1000 × 0,02 × 3 = R$ 60. Você devolve R$ 1.060."),
        ("practice", "Praticar", "Calcule os juros de R$ 500 a 1% ao mês por 6 meses. Depois diga o total a pagar."),
        ("check", "Verificar", "Confira se os juros são maiores quando o tempo é maior. Se triplicar o prazo, os juros triplicam?"),
        ("next", "Próximo passo", "Entender juros evita dívidas caras e ajuda a planejar compras."),
    ]),
    ("mat-orcamento", "Fazer um orçamento", "Entradas e saídas.", [
        ("explanation", "Entender", "Orçamento é a lista de tudo que entra (receita) e tudo que sai (despesa). Receita menos despesa mostra se sobra ou falta dinheiro no mês."),
        ("example", "Ver um exemplo", "Entra R$ 1.500. Sai: aluguel R$ 600, comida R$ 400, luz R$ 100. Sobram 1500 − 1100 = R$ 400."),
        ("practice", "Praticar", "Monte seu orçamento do mês em duas colunas: o que entra e o que sai. Some cada coluna."),
        ("check", "Verificar", "Se as despesas passaram das receitas, o resultado é negativo. Onde dá para reduzir sem perder o essencial?"),
        ("next", "Próximo passo", "Com o orçamento em mãos, você decide melhor sobre parcelas e poupança."),
    ]),
    ("mat-nota-fiscal", "Conferir uma nota fiscal", "Itens, valores e total.", [
        ("explanation", "Entender", "A nota fiscal lista cada produto, a quantidade, o preço unitário e o subtotal. No fim vem o total da compra e, às vezes, impostos."),
        ("example", "Ver um exemplo", "3 kg de arroz a R$ 5,00 dão R$ 15,00. 2 sabonetes a R$ 2,50 dão R$ 5,00. Total: R$ 20,00."),
        ("practice", "Praticar", "Pegue uma nota fiscal e confira se quantidade × preço unitário dá o subtotal de cada linha e se a soma das linhas dá o total."),
        ("check", "Verificar", "Se algum subtotal não bateu, refaça a multiplicação. Erros de caixa são mais comuns do que parecem."),
        ("next", "Próximo passo", "Conferir notas protege seu dinheiro e ajuda a controlar gastos."),
    ]),
    ("mat-conversao", "Converter unidades", "Metros, litros e gramas.", [
        ("explanation", "Entender", "Converter é trocar de unidade sem mudar a quantidade. No sistema métrico, cada unidade vale 10, 100 ou 1000 vezes a menor."),
        ("example", "Ver um exemplo", "1 km = 1000 m. 1 m = 100 cm. 1 kg = 1000 g. 1 litro = 1000 mL. Então 2,5 kg = 2500 g."),
        ("practice", "Praticar", "Converta: 3 m em cm, 2 litros em mL, 500 g em kg e 1500 m em km."),
        ("check", "Verificar", "Ao passar para uma unidade menor, o número aumenta. Para uma unidade maior, o número diminui. Suas respostas seguem isso?"),
        ("next", "Próximo passo", "Converter bem evita erro em receitas, obras e remédios."),
    ]),
    ("mat-tabela", "Ler uma tabela", "Organizar informação.", [
        ("explanation", "Entender", "Uma tabela organiza dados em linhas e colunas. O cruzamento de uma linha com uma coluna mostra a informação que você procura."),
        ("example", "Ver um exemplo", "Numa tabela de preços com produtos nas linhas e lojas nas colunas, para achar o preço do arroz na loja B basta seguir a linha do arroz até a coluna B."),
        ("practice", "Praticar", "Leia a tabela nutricional de um alimento e responda: quantas calorias tem por porção e quanto de açúcar?"),
        ("check", "Verificar", "Confira se você olhou a linha certa antes de ler o valor. Trocar de linha é o erro mais comum."),
        ("next", "Próximo passo", "Tabelas e gráficos são as duas formas de resumir dados."),
    ]),
    ("mat-simetria", "Simetria", "Formas espelhadas.", [
        ("explanation", "Entender", "Uma figura é simétrica quando dá para dobrá-la ao meio e as duas partes coincidem. A linha da dobra é o eixo de simetria."),
        ("example", "Ver um exemplo", "Uma borboleta e a letra A têm simetria vertical. O número 8 tem simetria vertical e horizontal."),
        ("practice", "Praticar", "Dobre uma folha ao meio, pinte metade de uma forma e recorte. Ao abrir, você vê uma figura simétrica."),
        ("check", "Verificar", "Para cada figura, pergunte: os dois lados são imagens espelhadas um do outro? Se sim, há simetria."),
        ("next", "Próximo passo", "Simetria aparece em arte, arquitetura e padrões de tecido."),
    ]),
    ("mat-escala", "Escalas e plantas", "Ler uma planta simples.", [
        ("explanation", "Entender", "Escala indica quantas vezes o desenho é menor que o real. Na escala 1:100, cada 1 cm no papel representa 100 cm, ou 1 metro, na realidade."),
        ("example", "Ver um exemplo", "Numa planta em escala 1:50, uma parede desenhada com 4 cm corresponde a 4 × 50 = 200 cm, ou 2 metros."),
        ("practice", "Praticar", "Meça um cômodo e desenhe a planta usando escala 1:100. Se a parede tem 3 m, ela aparece com 3 cm."),
        ("check", "Verificar", "Multiplique a medida do desenho pelo segundo número da escala. O resultado deve ser a medida real."),
        ("next", "Próximo passo", "Escalas permitem ler mapas, plantas e projetos."),
    ]),
    ("mat-tempo", "Calcular tempo", "Duração entre horários.", [
        ("explanation", "Entender", "Para achar a duração, subtraia o horário de início do horário de fim. Lembre que uma hora tem 60 minutos, então nem sempre dá para subtrair direto."),
        ("example", "Ver um exemplo", "De 14:30 a 16:10: de 14:30 a 16:00 são 90 minutos, mais 10 minutos, total 100 minutos, ou 1 hora e 40 minutos."),
        ("practice", "Praticar", "Calcule quanto tempo você levou: de 8:20 a 9:05, de 13:45 a 15:30 e de 22:10 a 23:00."),
        ("check", "Verificar", "Converta o resultado em horas e minutos. Se der mais de 60 minutos, transforme em hora cheia mais o resto."),
        ("next", "Próximo passo", "Calcular tempo ajuda a organizar rotina e transporte."),
    ]),
    ("mat-capacidade", "Medir capacidade", "Litros e mililitros.", [
        ("explanation", "Entender", "Capacidade é quanto um recipiente comporta, medida em litros (L) e mililitros (mL). Um litro tem mil mililitros."),
        ("example", "Ver um exemplo", "Uma garrafa de água de 500 mL é meio litro. Uma caixa de leite de 1 L tem 1000 mL."),
        ("practice", "Praticar", "Quantos copos de 200 mL cabem em 1 litro? E em 2 litros? Confira com uma jarra medidora."),
        ("check", "Verificar", "Some os mililitros: 5 copos de 200 mL dão 1000 mL, ou seja, 1 litro. A conta fechou?"),
        ("next", "Próximo passo", "Capacidade e volume aparecem em receitas, remédios e combustível."),
    ]),
    ("mat-numeros-romanos", "Números romanos", "I, V, X, L, C.", [
        ("explanation", "Entender", "Os romanos usavam letras para números: I = 1, V = 5, X = 10, L = 50, C = 100, D = 500 e M = 1000. Somam-se os valores, e quando um menor vem antes, subtrai-se."),
        ("example", "Ver um exemplo", "VI = 5 + 1 = 6. IV = 5 − 1 = 4. XIV = 10 + 4 = 14. MCMXC = 1000 + 900 + 90 = 1990."),
        ("practice", "Praticar", "Escreva em romanos: 7, 9, 24, 40 e 2024. Depois leia: XLII e XC."),
        ("check", "Verificar", "Se uma letra menor vem antes de uma maior, subtraia. Se vem depois, some. Suas respostas seguem essa regra?"),
        ("next", "Próximo passo", "Números romanos aparecem em relógios, capítulos e datas antigas."),
    ]),
    ("mat-pares", "Números pares e ímpares", "Reconhecer o padrão.", [
        ("explanation", "Entender", "Números pares podem ser divididos em dois grupos iguais: 2, 4, 6, 8, 10. Os ímpares deixam um sobrando: 1, 3, 5, 7, 9."),
        ("example", "Ver um exemplo", "Quatro meias formam dois pares, então 4 é par. Cinco meias deixam uma sobrando, então 5 é ímpar."),
        ("practice", "Praticar", "Separe os números de 1 a 20 em duas listas: pares e ímpares. Depois diga se 37 e 84 são pares ou ímpares."),
        ("check", "Verificar", "Todo número terminado em 0, 2, 4, 6 ou 8 é par. Terminado em 1, 3, 5, 7 ou 9 é ímpar. A regra funcionou?"),
        ("next", "Próximo passo", "Par e ímpar ajuda a entender divisão e números primos."),
    ]),
    ("mat-primos", "Números primos", "Só divide por 1 e ele mesmo.", [
        ("explanation", "Entender", "Número primo só pode ser dividido por 1 e por ele mesmo, sem deixar resto. O 1 não é primo, porque tem apenas um divisor."),
        ("example", "Ver um exemplo", "7 é primo: só divide por 1 e por 7. 8 não é primo, porque também divide por 2 e por 4."),
        ("practice", "Praticar", "Liste os números primos de 1 a 30. Teste dividindo cada número por 2, 3, 5 e 7."),
        ("check", "Verificar", "Um número par maior que 2 nunca é primo, porque divide por 2. Você excluiu todos eles da lista?"),
        ("next", "Próximo passo", "Primos são a base da fatoração e da segurança na internet."),
    ]),
    ("mat-mdc", "MDC e MMC", "Fatores comuns.", [
        ("explanation", "Entender", "O MDC é o maior número que divide dois valores ao mesmo tempo. O MMC é o menor número que os dois dividem. Ambos saem da fatoração em primos."),
        ("example", "Ver um exemplo", "Entre 12 e 18: o MDC é 6, porque 6 divide os dois. O MMC é 36, o primeiro múltiplo comum."),
        ("practice", "Praticar", "Calcule o MDC e o MMC de 8 e 12, e depois de 6 e 15."),
        ("check", "Verificar", "O MDC nunca é maior que o menor dos números. O MMC nunca é menor que o maior. Suas respostas respeitam isso?"),
        ("next", "Próximo passo", "MDC e MMC resolvem problemas de divisão de grupos e de encontros."),
    ]),
    ("mat-potencias", "Potências e raízes", "2² = 4, √9 = 3.", [
        ("explanation", "Entender", "Potência é multiplicar o mesmo número várias vezes: 2² é 2 × 2. A raiz é o caminho de volta: √9 pergunta qual número vezes ele mesmo dá 9."),
        ("example", "Ver um exemplo", "3² = 9 e 3³ = 27. Como 5 × 5 = 25, então √25 = 5."),
        ("practice", "Praticar", "Calcule: 4², 5², 2⁴ e as raízes √16, √36, √49."),
        ("check", "Verificar", "Confira elevando a raiz ao quadrado: se √36 = 6, então 6 × 6 precisa dar 36."),
        ("next", "Próximo passo", "Potências aparecem em juros compostos e em medidas de área."),
    ]),
    ("mat-desconto", "Calcular descontos", "Comparar preços.", [
        ("explanation", "Entender", "Desconto é uma redução sobre o preço. Calcula-se a porcentagem e subtrai-se do valor original. Comparar descontos ajuda a escolher a melhor compra."),
        ("example", "Ver um exemplo", "Um tênis de R$ 200 com 30% de desconto: desconto = 200 × 0,30 = R$ 60. Preço final = R$ 140."),
        ("practice", "Praticar", "Calcule o preço final: R$ 120 com 25% off, R$ 90 com 10% off e R$ 250 com 40% off."),
        ("check", "Verificar", "Quanto maior a porcentagem, maior a economia. Mas atenção: 30% de R$ 200 é mais que 50% de R$ 100."),
        ("next", "Próximo passo", "Comparar descontos é o que separa quem economiza de quem só acha que economizou."),
    ]),
    ("mat-planilha", "Matemática na planilha", "Somar colunas automaticamente.", [
        ("explanation", "Entender", "Uma planilha calcula com fórmulas. Toda fórmula começa com = e usa referências de células, como A1 ou B2."),
        ("example", "Ver um exemplo", "Para somar A1 até A10, escreva =SOMA(A1:A10). Para multiplicar A1 por B1, use =A1*B1."),
        ("practice", "Praticar", "Monte uma planilha com os gastos do mês na coluna A e use =SOMA para o total. Depois calcule a média com =MÉDIA."),
        ("check", "Verificar", "Confira o total somando na mão. Se a planilha e o papel derem o mesmo, a fórmula está certa."),
        ("next", "Próximo passo", "Planilhas automatizam orçamentos e qualquer conta repetida."),
    ]),
]
