import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { CEFR_LEVELS, getGoal, LANGUAGE_CATALOG, LEARNING_GOALS } from "@shared/institution";
import { ArrowRight, BookOpen, Flame, Gauge, Languages, Sparkles, Target } from "lucide-react";
import { Link } from "wouter";

export default function Dashboard() {
  const { user, isAuthenticated, loading } = useAuth();
  const profileQuery = trpc.profile.get.useQuery(undefined, { enabled: isAuthenticated });
  if (loading) return <InstitutionShell compact><div className="loading-page">Preparando tu espacio de aprendizaje…</div></InstitutionShell>;
  if (!isAuthenticated) return <InstitutionShell><section className="guest-dashboard"><p className="eyebrow">Mi espacio</p><h1>Tu recorrido merece <em>un lugar propio.</em></h1><p>Inicia sesión para conservar tu idioma de estudio, el diagnóstico orientativo, tus competencias de entrada, el avance y las prácticas que decidas guardar.</p><div><Link href="/diagnostico"><Button className="primary-cta">Diseñar mi recorrido <ArrowRight size={16} /></Button></Link><Button variant="outline" onClick={() => startLogin()}>Entrar</Button></div></section></InstitutionShell>;
  const profile = profileQuery.data;
  if (profileQuery.isLoading || !profile) return <InstitutionShell compact><div className="loading-page">Cargando tu ruta…</div></InstitutionShell>;
  const language = LANGUAGE_CATALOG.find((item) => item.code === profile.targetLanguageCode) ?? LANGUAGE_CATALOG[7];
  const goal = LEARNING_GOALS.find((item) => item.id === profile.learningGoal) ?? LEARNING_GOALS[0];
  const companion = profile.companionGoal ? getGoal(profile.companionGoal as typeof goal.id) : undefined;
  const completedProjects = profile.projectSubmissions.filter((submission) => submission.status === "completed");
  const currentIndex = CEFR_LEVELS.findIndex((level) => level.code === profile.currentLevel);
  return <InstitutionShell>
    <section className="dashboard-header"><div><p className="eyebrow">Hola, {user?.name?.split(" ")[0] ?? "estudiante"}</p><h1>Tu próximo paso está <em>claro.</em></h1><p>{goal.shortTitle} como entrada, {companion ? `${companion.shortTitle.toLocaleLowerCase()} como complemento` : `con ${language.name} como idioma de estudio`}.</p></div><Link href={profile.nextLesson ? `/lecciones/${profile.nextLesson.id}` : "/programas"}><Button className="primary-cta">Continuar aprendiendo <ArrowRight size={16} /></Button></Link></section>
    <section className="section-wrap dashboard-metrics"><article><Flame size={19} /><strong>{profile.streakDays}</strong><span>racha actual</span></article><article><Sparkles size={19} /><strong>{profile.xp}</strong><span>puntos de avance</span></article><article><BookOpen size={19} /><strong>{profile.lessonsCompleted}</strong><span>lecciones completas</span></article><article><Target size={19} /><strong>{profile.currentLevel}</strong><span>nivel de ruta</span></article></section>
    <section className="section-wrap dashboard-layout"><article className="progress-card"><div className="card-section-head"><div><p className="eyebrow">Progresión CEFR</p><h2>Tu recorrido en {language.name}</h2></div><Languages size={21} /></div><div className="cefr-track">{CEFR_LEVELS.map((level, index) => <div key={level.code} className={index < currentIndex ? "complete" : index === currentIndex ? "current" : ""}><span>{level.code}</span><div><strong>{level.title}</strong><small>{index < currentIndex ? "Consolidado" : index === currentIndex ? "En progreso" : "Por explorar"}</small></div></div>)}</div></article><aside className="next-card"><Gauge size={23} /><p className="eyebrow">Siguiente paso</p><h2>{profile.nextLesson?.title ?? "Explora un nuevo programa"}</h2><p>{profile.nextLesson?.objective ?? "Elige un objetivo para seguir construyendo tu ruta."}</p><div><span>{profile.nextLesson?.level ?? profile.currentLevel}</span><span>{profile.nextLesson?.minutes ?? 10} min</span></div><Link href={profile.nextLesson ? `/lecciones/${profile.nextLesson.id}` : "/programas"}>Abrir actividad <ArrowRight size={16} /></Link></aside></section>
    <section className="section-wrap dashboard-bottom"><article><p className="eyebrow">Facultad de entrada</p><h3>{goal.title}</h3><p>{goal.description}</p><Link href={`/programas?ruta=${goal.id}`}>Ver programa <ArrowRight size={15} /></Link></article>{companion && <article><p className="eyebrow">Complemento sugerido</p><h3>{companion.title}</h3><p>{companion.description}</p><Link href={`/programas?ruta=${companion.id}`}>Explorar complemento <ArrowRight size={15} /></Link></article>}<article><p className="eyebrow">Proyectos personales</p><h3>{completedProjects.length} evidencia{completedProjects.length === 1 ? "" : "s"} registrada{completedProjects.length === 1 ? "" : "s"}.</h3><p>Guarda un brief, un artefacto y una reflexión. La plataforma no evalúa ni certifica automáticamente tu proyecto.</p><Link href="/proyectos">Abrir estudio de proyectos <ArrowRight size={15} /></Link></article><article><p className="eyebrow">Tutor de aprendizaje</p><h3>Explica, practica o revisa contigo.</h3><p>Usa el tutor con tu idioma y nivel de ruta como contexto.</p><Link href="/tutor">Abrir tutor <ArrowRight size={15} /></Link></article></section><section className="section-wrap evidence-cta"><div><p className="eyebrow">Tus evidencias</p><h2>Un registro honesto de tu recorrido.</h2><p>Consulta o imprime únicamente las actividades y proyectos que hayas guardado como completados. No es una certificación oficial.</p></div><Link href="/mi-constancia"><Button variant="outline" className="soft-button">Ver mi constancia <ArrowRight size={16} /></Button></Link></section>
  </InstitutionShell>;
}
