import { InstitutionShell } from "@/components/InstitutionShell";
import { Button } from "@/components/ui/button";
import { COURSE_CATALOG, LEARNING_PROJECTS } from "@shared/content";
import { CEFR_LEVELS, CURRICULUM_LESSONS, LEARNING_GOALS, type LearningGoalId } from "@shared/institution";
import { ArrowRight, BookOpen, BrainCircuit, BriefcaseBusiness, CheckCircle2, Code2, Globe2, Landmark, Languages, type LucideIcon } from "lucide-react";
import { Link, useSearch } from "wouter";

const iconMap: Record<LearningGoalId, LucideIcon> = { everyday: Languages, technology: Globe2, coding: Code2, "ai-literacy": BrainCircuit, "digital-citizenship": Landmark, "professional-pathways": BriefcaseBusiness };

export default function Programs() {
  const activeGoal = (new URLSearchParams(useSearch()).get("ruta") ?? "everyday") as LearningGoalId;
  const selectedGoal = LEARNING_GOALS.find((goal) => goal.id === activeGoal) ?? LEARNING_GOALS[0];
  const lessons = CURRICULUM_LESSONS.filter((lesson) => lesson.goalId === selectedGoal.id);
  const courses = COURSE_CATALOG.filter((course) => course.goal === selectedGoal.id);
  const project = LEARNING_PROJECTS.find((item) => item.goalId === selectedGoal.id);
  const Icon = iconMap[selectedGoal.id];
  return <InstitutionShell>
    <section className="page-hero programs-hero"><p className="eyebrow">Facultades y programas</p><h1>Del objetivo real a una <em>capacidad demostrable.</em></h1><p>Lengua, ciudadanía digital, tecnología, programación, IA y trayectorias profesionales comparten una misma lógica: comprender una situación, practicar una acción y conservar evidencia de lo aprendido.</p></section>
    <section className="section-wrap program-tabs">{LEARNING_GOALS.map((goal) => { const GoalIcon = iconMap[goal.id]; return <Link key={goal.id} href={`/programas?ruta=${goal.id}`} className={goal.id === selectedGoal.id ? "active" : ""}><GoalIcon size={18} />{goal.shortTitle}</Link>; })}</section>
    <section className="section-wrap program-detail"><div className={`program-identity ${selectedGoal.color}`}><div className="program-icon"><Icon size={29} /></div><p className="eyebrow">Ruta seleccionada</p><h2>{selectedGoal.title}</h2><p>{selectedGoal.description}</p><div className="program-meta"><span>{selectedGoal.id === "everyday" ? "CEFR A1–C2" : "Seis etapas"}</span><span>Objetivos breves</span><span>Práctica guiada</span></div></div><div className="program-levels"><p className="eyebrow">Progresión</p><h2>Una escalera de práctica.</h2><p>{selectedGoal.id === "everyday" ? "El CEFR orienta el diseño de la facultad de Lenguas. No constituye una certificación." : "Las etapas organizan complejidad y autonomía; no certifican conocimiento ni sustituyen una evaluación profesional."}</p><div>{CEFR_LEVELS.map((level, index) => <article key={level.code} className={index === 0 ? "ready" : ""}><span>{level.code}</span><div><strong>{level.title}</strong><p>{level.description}</p></div>{index === 0 ? <CheckCircle2 size={18} /> : <span className="level-dot" />}</article>)}</div></div></section>
    <section className="section-wrap course-preview"><div className="section-heading"><div><p className="eyebrow">Cursos de la facultad</p><h2>Un curso organiza el camino.</h2></div><span>{courses.length} cursos iniciales</span></div><div className="course-preview-grid">{courses.length > 0 ? courses.map((course) => <article key={course.id}><span>{course.level}</span><h3>{course.title}</h3><p>{course.summary}</p><div>{course.outcomes.map((outcome) => <small key={outcome}>{outcome}</small>)}</div><Link href={`/lecciones/${lessons.find((lesson) => lesson.level === course.level)?.id ?? lessons[0]?.id ?? ""}`}>Ver primera actividad <ArrowRight size={15} /></Link></article>) : <article className="course-empty"><h3>Catálogo en construcción editorial</h3><p>La facultad ya dispone de actividades; el curso completo se ampliará con objetivos, fuentes y revisión antes de publicarse.</p></article>}</div></section>
    <section className="section-wrap lesson-preview"><div className="section-heading"><div><p className="eyebrow">Base curricular</p><h2>Primeras lecciones de la ruta.</h2></div><Link href="/biblioteca" className="text-cta">Abrir biblioteca <ArrowRight size={16} /></Link></div><div className="lesson-preview-grid">{lessons.map((lesson) => <Link href={`/lecciones/${lesson.id}`} key={lesson.id} className="lesson-preview-card"><span>{lesson.level}</span><div><small>{lesson.minutes} min · {lesson.activity === "code" ? "Código" : lesson.activity === "dialogue" ? "Diálogo" : "Práctica"}</small><h3>{lesson.title}</h3><p>{lesson.objective}</p></div><ArrowRight size={17} /></Link>)}</div><div className="program-actions"><Link href="/diagnostico"><Button className="primary-cta">Diseñar un recorrido personalizado <ArrowRight size={16} /></Button></Link>{project && <Link href={`/proyectos?proyecto=${project.id}`}><Button variant="outline" className="soft-button">Abrir desafío de proyecto <ArrowRight size={16} /></Button></Link>}</div></section>
    <section className="principles-strip"><BookOpen size={20} /><p>El CEFR guía la progresión lingüística. Las demás facultades usan objetivos verificables y reflexión; la plataforma no emite certificaciones oficiales.</p></section>
  </InstitutionShell>;
}
