import PublicShell from "@/components/PublicShell";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { BadgeCheck, FileSearch, ShieldAlert } from "lucide-react";
import { useState } from "react";

const copy = {
  es: { eyebrow: "Verificación", title: "Verifica un registro académico interno.", lead: "Introduce el identificador emitido por D.I.C.T. para confirmar si el registro interno sigue vigente. No se muestran datos personales ni se afirma acreditación externa.", identifier: "Identificador de verificación", placeholder: "Ej. DCT-AB12CD34", action: "Verificar identificador", noRecord: "No se encontró un registro interno vigente con ese identificador.", valid: "Registro interno válido", issued: "Emitido", ca: "CA registrados", note: "El resultado confirma únicamente un documento académico interno de D.I.C.T. No es un título oficial, una equivalencia universitaria ni una credencial ECTS." },
  pt: { eyebrow: "Verificação", title: "Verifica um registo académico interno.", lead: "Introduz o identificador emitido pela D.I.C.T. para confirmar se o registo interno continua válido. Não são mostrados dados pessoais nem é afirmada acreditação externa.", identifier: "Identificador de verificação", placeholder: "Ex. DCT-AB12CD34", action: "Verificar identificador", noRecord: "Não foi encontrado um registo interno válido com esse identificador.", valid: "Registo interno válido", issued: "Emitido", ca: "CA registados", note: "O resultado confirma apenas um documento académico interno da D.I.C.T. Não é um diploma oficial, equivalência universitária ou credencial ECTS." },
  en: { eyebrow: "Verification", title: "Verify an internal academic record.", lead: "Enter an identifier issued by D.I.C.T. to confirm whether the internal record remains valid. No personal data is shown and no external accreditation is claimed.", identifier: "Verification ID", placeholder: "E.g. DCT-AB12CD34", action: "Verify identifier", noRecord: "No current internal record was found for this identifier.", valid: "Valid internal record", issued: "Issued", ca: "Recorded CA", note: "The result only confirms an internal D.I.C.T. academic document. It is not an official degree, university equivalency or ECTS credential." },
};

export default function CertificateVerify() {
  const { locale } = useLanguage(); const text = copy[locale]; const [code, setCode] = useState(""); const [submittedCode, setSubmittedCode] = useState("");
  const verification = trpc.certificates.verify.useQuery({ verificationCode: submittedCode || "pending-id" }, { enabled: Boolean(submittedCode) });
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (code.trim()) setSubmittedCode(code.trim()); };
  return <PublicShell><section className="verify-page"><div><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.lead}</p></div><form onSubmit={submit} className="verify-form"><FileSearch size={25}/><label htmlFor="certificate-code">{text.identifier}</label><input id="certificate-code" value={code} onChange={event => setCode(event.target.value)} placeholder={text.placeholder}/><button disabled={verification.isFetching}>{text.action}</button></form>{verification.data && <section className={`verification-result ${verification.data.valid ? "valid" : "invalid"}`}>{verification.data.valid ? <BadgeCheck size={24}/> : <ShieldAlert size={24}/>}<div><b>{verification.data.valid ? text.valid : text.noRecord}</b>{verification.data.valid && <p>{text.issued}: {verification.data.issuedAt ? new Date(verification.data.issuedAt).toLocaleDateString(locale) : "—"} · {text.ca}: {verification.data.awardedCredits} · {verification.data.programVersion}</p>}</div></section>}{verification.error && <p className="verify-error">{verification.error.message}</p>}<aside className="verify-notice"><ShieldAlert size={18}/><p>{text.note}</p></aside></section></PublicShell>;
}
