import { courses, getCourse, getCourseDetail, trackLabels, type Locale } from "@shared/dictCatalog";
import { ArrowLeft, BookOpen, ClipboardCheck, FlaskConical, GraduationCap, ShieldCheck } from "lucide-react";
import { Link, useRoute } from "wouter";
import PublicShell from "@/components/PublicShell";
import { useLanguage } from "@/contexts/LanguageContext";

const copy: Record<Locale, { back: string; notFound: string; semester: string; hours: string; structured: string; objectives: string; competencies: string; syllabus: string; exercises: string; lab: string; project: string; ai: string; resources: string; assessment: string; assessmentText: string; rubric: string; prerequisites: string; noDetail: string }> = {
  es: { back: "Volver al catálogo", notFound: "Asignatura no encontrada.", semester: "Semestre", hours: "horas", structured: "FICHA ESTRUCTURADA", objectives: "Objetivos", competencies: "Competencias", syllabus: "Temario", exercises: "Ejercicios", lab: "Laboratorio", project: "Proyecto", ai: "Uso de IA", resources: "Bibliografía y recursos", assessment: "Evaluación", assessmentText: "La asignatura puede ajustar sus pesos, manteniendo evidencia práctica, documentación y una demostración de competencia.", rubric: "Rúbrica", prerequisites: "Prerrequisitos bloqueantes", noDetail: "La ficha ampliada se publica en la siguiente revisión curricular; esta unidad ya muestra su posición, requisitos y resultados de aprendizaje en el plan." },
  pt: { back: "Voltar ao catálogo", notFound: "Disciplina não encontrada.", semester: "Semestre", hours: "horas", structured: "FICHA ESTRUTURADA", objectives: "Objetivos", competencies: "Competências", syllabus: "Programa", exercises: "Exercícios", lab: "Laboratório", project: "Projeto", ai: "Uso de IA", resources: "Bibliografia e recursos", assessment: "Avaliação", assessmentText: "A disciplina pode ajustar os seus pesos, mantendo evidência prática, documentação e uma demonstração de competência.", rubric: "Rubrica", prerequisites: "Pré-requisitos bloqueantes", noDetail: "A ficha ampliada será publicada na próxima revisão curricular; esta unidade já apresenta posição, requisitos e resultados de aprendizagem no plano." },
  en: { back: "Back to catalog", notFound: "Course not found.", semester: "Semester", hours: "hours", structured: "STRUCTURED BRIEF", objectives: "Objectives", competencies: "Competencies", syllabus: "Syllabus", exercises: "Exercises", lab: "Laboratory", project: "Project", ai: "AI use", resources: "Reading & resources", assessment: "Assessment", assessmentText: "The course may adjust its weights while retaining practical evidence, documentation and a competency demonstration.", rubric: "Rubric", prerequisites: "Blocking prerequisites", noDetail: "The extended brief will be published in the next curriculum review; this unit already shows its placement, requirements and learning outcomes in the plan." },
};
function List({ title, items }: { title: string; items: string[] }) { return <section className="detail-list"><h2>{title}</h2><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></section>; }
export default function CourseDetail() {
  const [, params] = useRoute("/catalog/:code"); const course = getCourse(params?.code || ""); const { locale } = useLanguage(); const text = copy[locale];
  if (!course) return <PublicShell><section className="empty-state"><h1>404</h1><p>{text.notFound}</p><Link href="/catalog">{text.back}</Link></section></PublicShell>;
  const detail = getCourseDetail(course.code);
  return <PublicShell><section className="detail-hero"><Link href="/catalog" className="back-link"><ArrowLeft size={16}/>{text.back}</Link><div className="detail-kicker"><span>{course.code}</span><span>{text.semester} {course.semester} · {course.credits} CA · {course.hours} {text.hours}</span><span>{trackLabels[course.track][locale]}</span></div><h1>{course.title[locale]}</h1><p>{course.summary[locale]}</p><div className="detail-tags"><span>{course.entry} → {course.exit}</span><span>{text.prerequisites}: {course.prerequisites.length ? course.prerequisites.join(", ") : "—"}</span></div></section>
    {!detail ? <section className="library-note"><h2>{text.structured}</h2><p>{text.noDetail}</p></section> : <><section className="detail-two"><List title={text.objectives} items={detail.objectives[locale]} /><List title={text.competencies} items={detail.competencies[locale]} /></section><section className="detail-two"><List title={text.syllabus} items={detail.syllabus[locale]} /><List title={text.exercises} items={detail.exercises[locale]} /></section><section className="brief-grid"><article><FlaskConical size={21}/><h2>{text.lab}</h2><p>{detail.lab[locale]}</p></article><article><GraduationCap size={21}/><h2>{text.project}</h2><p>{detail.project[locale]}</p></article><article><ShieldCheck size={21}/><h2>{text.ai}</h2><p>{detail.aiPolicy[locale]}</p></article></section><section className="assessment-section"><div><span className="eyebrow">{text.assessment}</span><h2>15 / 30 / 35 / 10 / 10</h2><p>{text.assessmentText}</p>{detail.assessment.map(item => <div className="weight-row" key={item.label[locale]}><span>{item.label[locale]}</span><b>{item.weight}%</b><i style={{ width: `${item.weight * 2}%` }} /></div>)}</div><div><span className="eyebrow">{text.rubric}</span>{detail.rubric.map(item => <div className="rubric-row" key={item.criterion[locale]}><span>{item.criterion[locale]}</span><b>{item.weight}%</b></div>)}</div></section><section className="resources-section"><span className="eyebrow">{text.resources}</span><div>{detail.resources.map(resource => <a href={resource.url} target="_blank" rel="noreferrer" key={resource.url}><BookOpen size={16}/><span><b>{resource.title}</b><small>{resource.type} · {resource.access}{resource.license ? ` · ${resource.license}` : ""}</small></span></a>)}</div></section></>}</PublicShell>;
}
