import PublicShell from "@/components/PublicShell";
import { useLanguage } from "@/contexts/LanguageContext";
import { Cpu, FlaskConical, HardDrive, ShieldCheck } from "lucide-react";

const labContent = {
  es: { eyebrow: "Laboratorios guiados", title: "Práctica deliberada. Entornos autorizados.", lead: "Itinerarios técnicos que convierten conceptos en evidencia reproducible. Cada laboratorio fija límites de uso, recursos y una alternativa de menor coste cuando es viable.", metric: "entornos de práctica", guided: "LABORATORIO GUIADO", cpu: "Ruta CPU / bajo coste", standard: "Ruta estándar", limits: "Límite de uso", labs: [["ML aplicado", "Preparar datos, comparar modelos e interpretar métricas.", "Python, scikit-learn, datasets pequeños y 8 GB RAM.", "16 GB RAM y SSD para experimentos mayores.", "No usar datos personales sin evaluación de privacidad."], ["LLM y RAG", "Recuperar evidencia, evaluar respuestas y documentar guardrails.", "Modelos cuantizados, embeddings pequeños o API declarada.", "GPU de 8–16 GB VRAM para fine-tuning experimental.", "No cargar secretos, datos sensibles o material sin permiso."], ["Visión por computador", "Construir y evaluar un clasificador o detector trazable.", "Transfer learning limitado en CPU o notebooks gratuitos.", "GPU de 8 GB VRAM y PyTorch.", "Revisar licencia, consentimiento y sesgos del dataset."], ["Cloud y entrega", "Contenerizar, automatizar pruebas, desplegar y observar un servicio.", "Docker local, compose y cuentas gratuitas con control de coste.", "Entorno cloud aislado con presupuesto y alertas.", "No exponer claves; destruir recursos de práctica."], ["Ciberseguridad defensiva", "Identificar y corregir debilidades en aplicaciones de laboratorio.", "OWASP Juice Shop local y navegador, con 8 GB RAM.", "Máquina virtual o red de laboratorio aislada.", "Solo objetivos locales, aislados y autorizados."]] },
  pt: { eyebrow: "Laboratórios guiados", title: "Prática deliberada. Ambientes autorizados.", lead: "Itinerários técnicos que transformam conceitos em evidência reprodutível. Cada laboratório fixa limites, recursos e uma alternativa de menor custo quando viável.", metric: "ambientes de prática", guided: "LABORATÓRIO GUIADO", cpu: "Rota CPU / baixo custo", standard: "Rota padrão", limits: "Limite de uso", labs: [["ML aplicado", "Preparar dados, comparar modelos e interpretar métricas.", "Python, scikit-learn, datasets pequenos e 8 GB RAM.", "16 GB RAM e SSD para experiências maiores.", "Não usar dados pessoais sem avaliação de privacidade."], ["LLM e RAG", "Recuperar evidência, avaliar respostas e documentar guardrails.", "Modelos quantizados, embeddings pequenos ou API declarada.", "GPU de 8–16 GB VRAM para fine-tuning experimental.", "Não carregar segredos, dados sensíveis ou material sem permissão."], ["Visão por computador", "Construir e avaliar um classificador ou detetor rastreável.", "Transfer learning limitado em CPU ou notebooks gratuitos.", "GPU de 8 GB VRAM e PyTorch.", "Rever licença, consentimento e vieses do dataset."], ["Cloud e entrega", "Contentorizar, automatizar testes, implantar e observar um serviço.", "Docker local, compose e contas gratuitas com controlo de custo.", "Ambiente cloud isolado com orçamento e alertas.", "Não expor chaves; destruir recursos de prática."], ["Cibersegurança defensiva", "Identificar e corrigir fraquezas em aplicações de laboratório.", "OWASP Juice Shop local e navegador, com 8 GB RAM.", "Máquina virtual ou rede de laboratório isolada.", "Apenas objetivos locais, isolados e autorizados."]] },
  en: { eyebrow: "Guided laboratories", title: "Deliberate practice. Authorized environments.", lead: "Technical pathways that turn concepts into reproducible evidence. Every laboratory defines boundaries, resources and a lower-cost alternative when viable.", metric: "practice environments", guided: "GUIDED LAB", cpu: "CPU / low-cost path", standard: "Standard path", limits: "Use boundary", labs: [["Applied ML", "Prepare data, compare models and interpret metrics.", "Python, scikit-learn, small datasets and 8 GB RAM.", "16 GB RAM and SSD for larger experiments.", "Do not use personal data without privacy review."], ["LLM & RAG", "Retrieve evidence, assess responses and document guardrails.", "Quantized models, small embeddings or a declared API.", "8–16 GB VRAM GPU for experimental fine-tuning.", "Do not load secrets, sensitive data or unpermitted material."], ["Computer Vision", "Build and assess a traceable classifier or detector.", "CPU-limited transfer learning or free notebooks.", "8 GB VRAM GPU and PyTorch.", "Review data license, consent and bias."], ["Cloud & Delivery", "Containerize, automate tests, deploy and observe a service.", "Local Docker, compose and free-tier accounts with cost controls.", "Isolated cloud environment with a budget and alerts.", "Do not expose keys; destroy practice resources."], ["Defensive Cybersecurity", "Identify and remediate weaknesses in laboratory applications.", "Local OWASP Juice Shop and browser with 8 GB RAM.", "Isolated VM or lab network.", "Only local, isolated and authorized targets."]] },
};

export default function Labs() {
  const { locale } = useLanguage(); const text = labContent[locale];
  return <PublicShell><section className="page-intro"><div><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.lead}</p></div><div className="intro-stat"><b>05</b><span>{text.metric}</span></div></section><section className="labs-grid">{text.labs.map(([name, outcome, cpu, standard, limit]) => <article key={name}><header><FlaskConical size={19}/><span>{text.guided}</span></header><h2>{name}</h2><p>{outcome}</p><div><Cpu size={15}/><b>{text.cpu}</b><span>{cpu}</span></div><div><HardDrive size={15}/><b>{text.standard}</b><span>{standard}</span></div><aside><ShieldCheck size={15}/><span><b>{text.limits}:</b> {limit}</span></aside></article>)}</section></PublicShell>;
}
