import { ExternalLink, FileText, Github, Scale, Shield, Sparkles } from "lucide-react";
import PublicShell from "@/components/PublicShell";
import { useLanguage } from "@/contexts/LanguageContext";

const resources = [
  { icon: Sparkles, title: "Hugging Face LLM Course", url: "https://huggingface.co/learn/llm-course/en/chapter1/1", access: "FREE" }, { icon: Github, title: "mlabonne/llm-course", url: "https://github.com/mlabonne/llm-course", access: "OPEN SOURCE · Apache-2.0" }, { icon: Shield, title: "OWASP Web Security Testing Guide", url: "https://owasp.org/www-project-web-security-testing-guide/", access: "FREE" }, { icon: Github, title: "OWASP Juice Shop", url: "https://github.com/juice-shop/juice-shop", access: "OPEN SOURCE · MIT" }, { icon: FileText, title: "NIST AI 600-1", url: "https://doi.org/10.6028/NIST.AI.600-1", access: "FREE" }, { icon: Scale, title: "W3C WCAG 2.2", url: "https://www.w3.org/TR/WCAG22/", access: "FREE" },
];

const copy = {
  es: { eyebrow: "Biblioteca académica", title: "Fuentes antes que tendencias.", lead: "Recursos seleccionados por autoridad, licencia, mantenibilidad y utilidad pedagógica. Cada enlace permanece en su fuente original.", metric: "código-abierto-primero", noteTitle: "Licencias, privacidad y uso responsable", note: "La plataforma enlaza recursos originales y no reproduce materiales protegidos. Antes de usar un recurso en un proyecto, el estudiante debe verificar su licencia, restricciones de datos, requisitos de atribución y compatibilidad con el uso previsto.", items: [["Documentación oficial", "Transformers, conjuntos de datos, tokenizadores, fine-tuning y demostraciones de modelos."], ["Repositorio", "Fundamentos de LLM, hojas de ruta de investigación e ingeniería con cuadernos."], ["Estándar de seguridad", "Marco de prácticas para pruebas de seguridad de aplicaciones y servicios web."], ["Laboratorio aislado", "Aplicación deliberadamente insegura para entornos de aprendizaje autorizados."], ["Investigación y gobernanza", "Perfil de gestión de riesgos de IA generativa y orientación para IA confiable."], ["Estándar de accesibilidad", "Orientación para contenido perceptible, operable, comprensible y robusto."]] },
  pt: { eyebrow: "Biblioteca académica", title: "Fontes antes de tendências.", lead: "Recursos selecionados por autoridade, licença, manutenção e utilidade pedagógica. Cada ligação permanece na fonte original.", metric: "código-aberto-primeiro", noteTitle: "Licenças, privacidade e uso responsável", note: "A plataforma liga recursos originais e não reproduz materiais protegidos. Antes de usar um recurso num projeto, o estudante deve verificar a licença, restrições de dados, requisitos de atribuição e compatibilidade com o uso previsto.", items: [["Documentação oficial", "Transformers, conjuntos de dados, tokenizadores, fine-tuning e demonstrações de modelos."], ["Repositório", "Fundamentos de LLM, roteiros de investigação e engenharia com cadernos."], ["Norma de segurança", "Estrutura de práticas para testes de segurança de aplicações e serviços web."], ["Laboratório isolado", "Aplicação deliberadamente insegura para ambientes de aprendizagem autorizados."], ["Investigação e governação", "Perfil de gestão de riscos de IA generativa e orientação para IA confiável."], ["Norma de acessibilidade", "Orientação para conteúdo percetível, operável, compreensível e robusto."]] },
  en: { eyebrow: "Academic library", title: "Sources before trends.", lead: "Resources selected for authority, license, maintenance and pedagogical utility. Every link remains at its original source.", metric: "open-source-first", noteTitle: "Licenses, privacy and responsible use", note: "The platform links to original resources and does not reproduce protected materials. Before using a resource in a project, students must check its license, data restrictions, attribution requirements and compatibility with intended use.", items: [["Official documentation", "Transformers, datasets, tokenizers, fine-tuning and model demos."], ["Repository", "LLM fundamentals, research and engineering roadmaps with notebooks."], ["Security standard", "A practice framework for web application and service security testing."], ["Isolated lab", "Deliberately insecure application for authorized training environments."], ["Research & governance", "Generative-AI risk management profile and trustworthy-AI guidance."], ["Accessibility standard", "Guidance for perceptible, operable, understandable and robust content."]] },
};

export default function Library() {
  const { locale } = useLanguage(); const text = copy[locale];
  return <PublicShell><section className="page-intro"><div><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.lead}</p></div><div className="intro-stat"><b>01</b><span>{text.metric}</span></div></section><section className="library-grid">{resources.map((resource, index) => <a className="resource-card" href={resource.url} target="_blank" rel="noreferrer" key={resource.title}><resource.icon size={20}/><div><span>{text.items[index]?.[0]}</span><h2>{resource.title}</h2><p>{text.items[index]?.[1]}</p><b>{resource.access}</b></div><ExternalLink size={16}/></a>)}</section><section className="library-note"><h2>{text.noteTitle}</h2><p>{text.note}</p></section></PublicShell>;
}
