import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { FolderGit2, Globe2, LockKeyhole, Plus, Sparkles } from "lucide-react";
import { useState } from "react";

const copy = {
  es: { eyebrow: "EVIDENCIA PROFESIONAL", title: "Proyectos con trazabilidad.", lead: "Registra artefactos de aprendizaje, enlaza tu repositorio y decide cuándo podrán aparecer en tu portfolio público.", new: "Nuevo proyecto", titleLabel: "Título", course: "Asignatura (opcional)", summary: "Resumen", technologies: "Tecnologías", titlePlaceholder: "Línea base de observabilidad para un servicio", technologiesPlaceholder: "TypeScript, Docker, OpenTelemetry", summaryPlaceholder: "Describe el problema, la decisión técnica, las evidencias y las limitaciones.", public: "Visible en el portfolio público", private: "Visible solo para ti", create: "Crear proyecto", responsible: "Entrega responsable", responsibleText: "Adjunta únicamente materiales que puedas compartir. Los binarios van al almacenamiento de archivos; la base de datos conserva solo referencias y metadatos.", qualificationText: "Una publicación pública no certifica empleo ni equivale a un título universitario oficial.", portfolio: "MI PORTFOLIO", count: "proyectos registrados", loading: "Cargando proyectos…", empty: "Aún no hay proyectos. Crea uno para construir evidencia técnica verificable.", publicTag: "PÚBLICO", privateTag: "PRIVADO" },
  pt: { eyebrow: "EVIDÊNCIA PROFISSIONAL", title: "Projetos com rastreabilidade.", lead: "Regista artefactos de aprendizagem, liga o teu repositório e decide quando podem aparecer no teu portfólio público.", new: "Novo projeto", titleLabel: "Título", course: "Disciplina (opcional)", summary: "Resumo", technologies: "Tecnologias", titlePlaceholder: "Base de observabilidade para um serviço", technologiesPlaceholder: "TypeScript, Docker, OpenTelemetry", summaryPlaceholder: "Descreve o problema, a decisão técnica, as evidências e as limitações.", public: "Visível no portfólio público", private: "Visível apenas para ti", create: "Criar projeto", responsible: "Entrega responsável", responsibleText: "Anexa apenas materiais que possas partilhar. Os binários vão para o armazenamento de ficheiros; a base de dados conserva apenas referências e metadados.", qualificationText: "Uma publicação pública não certifica emprego nem equivale a um diploma universitário oficial.", portfolio: "O MEU PORTFÓLIO", count: "projetos registados", loading: "A carregar projetos…", empty: "Ainda não há projetos. Cria um para construir evidência técnica verificável.", publicTag: "PÚBLICO", privateTag: "PRIVADO" },
  en: { eyebrow: "PROFESSIONAL EVIDENCE", title: "Projects with traceability.", lead: "Record learning artefacts, link your repository and decide when they may appear in your public portfolio.", new: "New project", titleLabel: "Title", course: "Course (optional)", summary: "Summary", technologies: "Technologies", titlePlaceholder: "Observability baseline for a service", technologiesPlaceholder: "TypeScript, Docker, OpenTelemetry", summaryPlaceholder: "Describe the problem, technical decision, evidence and limitations.", public: "Visible in the public portfolio", private: "Visible only to you", create: "Create project", responsible: "Responsible submission", responsibleText: "Attach only material you may share. Binary files go to file storage; the database retains only references and metadata.", qualificationText: "A public entry does not certify employment or equal an official university degree.", portfolio: "MY PORTFOLIO", count: "registered projects", loading: "Loading projects…", empty: "There are no projects yet. Create one to build verifiable technical evidence.", publicTag: "PUBLIC", privateTag: "PRIVATE" },
};

function ProjectEvidence({ projectId, label }: { projectId: number; label: string }) {
  const files = trpc.student.projectFiles.useQuery({ projectId });
  if (!files.data?.length) return null;
  return <div className="file-list"><b>{label}</b>{files.data.map(file => <a href={file.downloadUrl} key={file.id} target="_blank" rel="noreferrer">{file.displayName} <span>{Math.ceil(file.sizeBytes / 1024)} KB</span></a>)}</div>;
}

export default function ProjectsPage() {
  const { locale } = useLanguage(); const text = copy[locale]; const { isAuthenticated } = useAuth(); const projects = trpc.student.projects.useQuery(undefined, { enabled: isAuthenticated });
  const create = trpc.student.createProject.useMutation({ onSuccess: () => { projects.refetch(); setTitle(""); setSummary(""); setTechnologyText(""); } });
  const attach = trpc.student.attachProjectFile.useMutation();
  const [title, setTitle] = useState(""); const [summary, setSummary] = useState(""); const [courseCode, setCourseCode] = useState(""); const [technologyText, setTechnologyText] = useState(""); const [isPublic, setIsPublic] = useState(false);
  const attachmentLabel = locale === "es" ? "Adjuntar evidencia (máx. 5 MB)" : locale === "pt" ? "Anexar evidência (máx. 5 MB)" : "Attach evidence (max. 5 MB)";
  const evidenceLabel = locale === "es" ? "Evidencias adjuntas" : locale === "pt" ? "Evidências anexadas" : "Attached evidence";
  const attachFile = async (projectId: number, file?: File) => {
    if (!file || file.size > 5_000_000) return;
    const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ""; bytes.forEach(byte => { binary += String.fromCharCode(byte); });
    const acceptedTypes = ["text/plain", "text/markdown", "application/json", "application/pdf", "application/zip", "image/png", "image/jpeg"] as const;
    const mimeType = acceptedTypes.includes(file.type as typeof acceptedTypes[number]) ? file.type as typeof acceptedTypes[number] : "text/plain";
    attach.mutate({ projectId, displayName: file.name, mimeType, base64Content: btoa(binary), accessLevel: "private" });
  };
  return <DashboardLayout><section className="projects-page"><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.lead}</p><section className="project-workspace"><form onSubmit={event => { event.preventDefault(); create.mutate({ title, summary, courseCode: courseCode || undefined, technologies: technologyText.split(",").map(item => item.trim()).filter(Boolean), visibility: isPublic ? "public" : "private" }); }}><h2>{text.new}</h2><label>{text.titleLabel}<input required minLength={4} value={title} onChange={event => setTitle(event.target.value)} placeholder={text.titlePlaceholder} /></label><label>{text.course}<input value={courseCode} onChange={event => setCourseCode(event.target.value.toUpperCase())} pattern="DCT-[0-9]{3}" placeholder="DCT-302" /></label><label>{text.summary}<textarea required minLength={20} value={summary} onChange={event => setSummary(event.target.value)} rows={4} placeholder={text.summaryPlaceholder} /></label><label>{text.technologies}<input value={technologyText} onChange={event => setTechnologyText(event.target.value)} placeholder={text.technologiesPlaceholder} /></label><label className="project-visibility"><input type="checkbox" checked={isPublic} onChange={event => setIsPublic(event.target.checked)}/>{isPublic ? <Globe2 size={16}/> : <LockKeyhole size={16}/>}<span>{isPublic ? text.public : text.private}</span></label><button disabled={create.isPending}><Plus size={16}/>{text.create}</button>{create.error && <small className="project-error">{create.error.message}</small>}</form><aside><Sparkles size={18}/><h3>{text.responsible}</h3><p>{text.responsibleText}</p><p>{text.qualificationText}</p></aside></section><section className="project-list"><header><div><span className="eyebrow">{text.portfolio}</span><h2>{projects.data?.length ?? 0} {text.count}</h2></div><FolderGit2 size={21}/></header>{projects.isLoading && <p>{text.loading}</p>}{projects.data?.length === 0 && <p className="empty-projects">{text.empty}</p>}{projects.data?.map(project => <article key={project.id}><div><span>{project.visibility === "public" ? text.publicTag : text.privateTag}</span><h3>{project.title}</h3><p>{project.summary}</p><label className="file-attach">{attachmentLabel}<input type="file" accept=".txt,.md,.json,.pdf,.zip,.png,.jpg,.jpeg" onChange={event => attachFile(project.id, event.target.files?.[0])}/></label>{attach.error && <small className="project-error">{attach.error.message}</small>}<ProjectEvidence projectId={project.id} label={evidenceLabel}/></div><div className="technology-list">{project.technologies.map(tech => <i key={tech}>{tech}</i>)}</div></article>)}</section></section></DashboardLayout>;
}
