import DashboardLayout from "@/components/DashboardLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { getCourse } from "@shared/dictCatalog";
import { BookOpenCheck, BrainCircuit, FileBadge, FolderGit2, TrendingUp } from "lucide-react";
import { Link } from "wouter";

const text = {
  es: { title: "Panel de aprendizaje", eyebrow: "Datos de demostración", lead: "Tu progreso se transforma en evidencia: proyectos, competencias, CA y documentación.", credits: "CA obtenidos", competencies: "Competencias", projects: "Proyectos", documents: "Documentos", completed: "materias completadas", evidence: "evidencias registradas", personal: "del portfolio personal", internal: "internos, no oficiales", verified: "S1–S3 verificados", level: "4 en nivel C", public: "2 públicos", path: "Ruta actual", next: "Evidencia próxima", review: "Revisión de proyecto", assessment: "Entrega una evaluación comparativa, el repositorio documentado y una nota de reproducibilidad. La rúbrica valora corrección, arquitectura, seguridad y comunicación.", rubric: "Ver rúbrica y asignatura", completedStatus: "completado", activeStatus: "en curso", pendingStatus: "pendiente", record: "DOCUMENTACIÓN ACADÉMICA INTERNA", recordNote: "Este panel y cualquier certificado o transcript emitido por la plataforma no constituyen título oficial ni equivalencia universitaria." },
  pt: { title: "Painel de aprendizagem", eyebrow: "Dados de demonstração", lead: "O teu progresso transforma-se em evidência: projetos, competências, CA e documentação.", credits: "CA obtidos", competencies: "Competências", projects: "Projetos", documents: "Documentos", completed: "disciplinas concluídas", evidence: "evidências registadas", personal: "do portfólio pessoal", internal: "internos, não oficiais", verified: "S1–S3 verificados", level: "4 no nível C", public: "2 públicos", path: "Percurso atual", next: "Próxima evidência", review: "Revisão de projeto", assessment: "Entrega uma avaliação comparativa, o repositório documentado e uma nota de reprodutibilidade. A rúbrica avalia correção, arquitetura, segurança e comunicação.", rubric: "Ver rúbrica e disciplina", completedStatus: "concluído", activeStatus: "em curso", pendingStatus: "pendente", record: "DOCUMENTAÇÃO ACADÉMICA INTERNA", recordNote: "Este painel e qualquer certificado ou transcript emitido pela plataforma não constituem diploma oficial ou equivalência universitária." },
  en: { title: "Learning dashboard", eyebrow: "Demonstration data", lead: "Your progress becomes evidence: projects, competencies, CA and documentation.", credits: "Earned CA", competencies: "Competencies", projects: "Projects", documents: "Documents", completed: "completed courses", evidence: "recorded evidence", personal: "in your personal portfolio", internal: "internal, not official", verified: "S1–S3 verified", level: "4 at level C", public: "2 public", path: "Current pathway", next: "Next evidence", review: "Project review", assessment: "Submit a comparative assessment, documented repository and reproducibility note. The rubric assesses correctness, architecture, security and communication.", rubric: "View rubric and course", completedStatus: "complete", activeStatus: "in progress", pendingStatus: "pending", record: "INTERNAL ACADEMIC DOCUMENTATION", recordNote: "This dashboard and any certificate or transcript issued by the platform are not an official degree or university equivalency." },
};

export default function StudentDashboard() {
  const { locale } = useLanguage(); const copy = text[locale]; const { isAuthenticated } = useAuth(); const { data } = trpc.student.dashboard.useQuery(undefined, { enabled: isAuthenticated });
  const activeCourseTitle = getCourse("DCT-301")?.title[locale] ?? "DCT-301";
  const hasPersonalRecords = Boolean(data?.transcript.length);
  const cards = [{ label: copy.credits, value: hasPersonalRecords ? `${data?.credits} / 300` : "84 / 300", icon: TrendingUp, note: hasPersonalRecords ? `${data?.coursesCompleted} ${copy.completed}` : copy.verified }, { label: copy.competencies, value: hasPersonalRecords ? String(data?.coursesCompleted ?? 0) : "12", icon: BrainCircuit, note: hasPersonalRecords ? copy.evidence : copy.level }, { label: copy.projects, value: hasPersonalRecords ? String(data?.projects ?? 0).padStart(2, "0") : "05", icon: FolderGit2, note: hasPersonalRecords ? copy.personal : copy.public }, { label: copy.documents, value: hasPersonalRecords ? String(data?.transcript.length ?? 0).padStart(2, "0") : "03", icon: FileBadge, note: copy.internal }];
  const steps = locale === "es" ? [["Dataset, licencia y diccionario de variables", copy.completedStatus], ["Comparación reproducible de modelos", copy.activeStatus], ["Informe de límites y riesgos", copy.pendingStatus]] : locale === "pt" ? [["Dataset, licença e dicionário de variáveis", copy.completedStatus], ["Comparação reprodutível de modelos", copy.activeStatus], ["Relatório de limites e riscos", copy.pendingStatus]] : [["Dataset, license and variable dictionary", copy.completedStatus], ["Reproducible model comparison", copy.activeStatus], ["Limits and risk report", copy.pendingStatus]];
  return <DashboardLayout><section className="student-dashboard"><span className="eyebrow">{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.lead}</p><div className="student-stat-grid">{cards.map(card => <article key={card.label}><card.icon size={19}/><span>{card.label}</span><b>{card.value}</b><small>{card.note}</small></article>)}</div><section className="dashboard-split"><article className="dashboard-panel"><header><div><span className="eyebrow">{copy.path}</span><h2>DCT-301 · {activeCourseTitle}</h2></div><span className="progress-chip">68%</span></header><div className="progress-line"><i style={{ width: "68%" }} /></div><div className="module-list">{steps.map(([label, status], index) => <p key={label}><span>{String(index + 1).padStart(2, "0")}</span>{label}<b>{status}</b></p>)}</div></article><article className="dashboard-panel"><header><div><span className="eyebrow">{copy.next}</span><h2>{copy.review}</h2></div><BookOpenCheck size={22}/></header><p>{copy.assessment}</p><Link className="dashboard-button" href="/catalog/DCT-301">{copy.rubric}</Link></article></section><section className="internal-record"><span>{copy.record}</span><p>{copy.recordNote}</p></section></section></DashboardLayout>;
}
