import { type Message, AIChatBox } from "@/components/AIChatBox";
import DashboardLayout from "@/components/DashboardLayout";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, ShieldCheck } from "lucide-react";
import { useState } from "react";

const tutorCopy = {
  es: { eyebrow: "Tutor académico", title: "Aprende el razonamiento, no solo la respuesta.", lead: "El tutor explica conceptos, formula preguntas socráticas, plantea ejercicios y ayuda a preparar una defensa. No resuelve íntegramente evaluaciones calificadas.", modesLabel: "Modo del tutor", explain: "Explicar", socratic: "Socrático", hint: "Pista", practice: "Práctica", interview: "Entrevista", defense: "Defensa", empty: "Formula una duda sobre el programa o selecciona una práctica guiada.", placeholder: "Escribe tu pregunta académica…", suggestions: ["Explícame cómo evaluar un modelo de clasificación sin darme la solución del proyecto.", "Hazme tres preguntas socráticas sobre RAG y espera mis respuestas.", "Simula una entrevista técnica sobre estructuras de datos."], scope: "Límites pedagógicos", scopeText: "El tutor no califica, no modifica notas, no desbloquea asignaturas y no sustituye la evidencia del estudiante. En seguridad, el apoyo se limita a entornos legales y autorizados." },
  pt: { eyebrow: "Tutor académico", title: "Aprende o raciocínio, não apenas a resposta.", lead: "O tutor explica conceitos, formula perguntas socráticas, propõe exercícios e ajuda a preparar uma defesa. Não resolve integralmente avaliações classificadas.", modesLabel: "Modo do tutor", explain: "Explicar", socratic: "Socrático", hint: "Pista", practice: "Prática", interview: "Entrevista", defense: "Defesa", empty: "Coloca uma questão sobre o programa ou seleciona uma prática guiada.", placeholder: "Escreve a tua questão académica…", suggestions: ["Explica como avaliar um modelo de classificação sem dar a solução do projeto.", "Faz três perguntas socráticas sobre RAG e espera as minhas respostas.", "Simula uma entrevista técnica sobre estruturas de dados."], scope: "Limites pedagógicos", scopeText: "O tutor não classifica, não altera notas, não desbloqueia disciplinas e não substitui a evidência do estudante. Em segurança, o apoio limita-se a ambientes legais e autorizados." },
  en: { eyebrow: "Academic tutor", title: "Learn the reasoning, not merely the answer.", lead: "The tutor explains concepts, asks Socratic questions, creates practice and helps prepare a defense. It does not complete graded assessments for the student.", modesLabel: "Tutor mode", explain: "Explain", socratic: "Socratic", hint: "Hint", practice: "Practice", interview: "Interview", defense: "Defense", empty: "Ask a question about the program or select a guided practice prompt.", placeholder: "Write your academic question…", suggestions: ["Explain how to evaluate a classification model without giving me the project solution.", "Ask me three Socratic questions about RAG and wait for my answers.", "Simulate a technical interview about data structures."], scope: "Pedagogical boundaries", scopeText: "The tutor does not grade, alter grades, unlock courses or replace student evidence. For security, support is restricted to legal, authorized environments." },
};

export default function TutorPage() {
  const { locale } = useLanguage(); const text = tutorCopy[locale];
  const [mode, setMode] = useState<"explain" | "socratic" | "hint" | "practice" | "interview" | "defense">("explain");
  const [messages, setMessages] = useState<Message[]>([]);
  const tutor = trpc.tutor.ask.useMutation({ onSuccess: result => setMessages(previous => [...previous, { role: "assistant", content: result.reply }]) });
  const modes = [{ key: "explain", label: text.explain }, { key: "socratic", label: text.socratic }, { key: "hint", label: text.hint }, { key: "practice", label: text.practice }, { key: "interview", label: text.interview }, { key: "defense", label: text.defense }] as const;
  const send = (message: string) => { setMessages(previous => [...previous, { role: "user", content: message }]); tutor.mutate({ message, mode, locale, courseCode: "DCT-401" }); };
  return <DashboardLayout><section className="tutor-page"><div className="tutor-heading"><div><span className="eyebrow">{text.eyebrow}</span><h1>{text.title}</h1><p>{text.lead}</p></div><BrainCircuit size={42}/></div><div className="tutor-mode-row" aria-label={text.modesLabel}>{modes.map(item => <button onClick={() => setMode(item.key)} className={mode === item.key ? "active" : ""} key={item.key}>{item.label}</button>)}</div><AIChatBox messages={messages} onSendMessage={send} isLoading={tutor.isPending} height="500px" emptyStateMessage={text.empty} placeholder={text.placeholder} suggestedPrompts={text.suggestions} className="tutor-chat"/><aside className="tutor-policy"><ShieldCheck size={17}/><div><b>{text.scope}</b><p>{text.scopeText}</p></div></aside>{tutor.error && <p className="tutor-error">{tutor.error.message}</p>}</section></DashboardLayout>;
}
